-- Decompiled with the Synapse X Luau decompiler.

print("Running Bot Script");

task.wait(0.09);

local l__Value__1 = script.LinkedModel.Value;
local l__Debris__2 = game:GetService("Debris");
local l__Humanoid__3 = l__Value__1.Humanoid;

game:GetService("ScriptContext").Error:Connect(function(Error, trace, erroredScript)
	if erroredScript == script then
		warn("Error generated by: " .. l__Humanoid__3.Parent.Name)
		warn(Error)
	end
end)

local l__Torso__4 = l__Value__1.Torso;
local l__Stats__5 = l__Value__1.Stats;
local v6 = require(workspace.CFrameInterpolator);
math.randomseed(tick());
local l__Weld__7 = l__Value__1.Main.RightHip.Weld;
local l__Weld__8 = l__Value__1.Main.LeftHip.Weld;
local l__Weld__9 = l__Value__1.RightLeg.Upper.Knee.Weld;
local l__Weld__10 = l__Value__1.LeftLeg.Upper.Knee.Weld;
local l__Weld__11 = l__Value__1.RightLeg.Lower.Ankle.Weld;
local l__Weld__12 = l__Value__1.LeftLeg.Lower.Ankle.Weld;
local l__Weld__13 = l__Value__1.Main.RightShoulder.Weld;
local l__Weld__14 = l__Value__1.Main.LeftShoulder.Weld;
local l__Weld__15 = l__Value__1.RightArm.Wrist.Weld;
playerStats = game.Players.LocalPlayer.Stats
l__Humanoid__3.MaxHealth = l__Stats__5.Health.Value * (playerStats.Difficulty.Value / 3);
l__Humanoid__3.Health = l__Humanoid__3.MaxHealth;
l__Humanoid__3.WalkSpeed = l__Stats__5.Speed.Value;
local l__Value__16 = l__Stats__5.Range.Value;
local v17 = math.random(0, 1);
local l__Path__18 = l__Stats__5.Path;
local v19 = false;
local v20 = l__Path__18:GetChildren();
if #v20 > 0 then
	v19 = true;
end;
l__Humanoid__3.AutoRotate = false;
local v21 = l__Torso__4:findFirstChild("BodyGyro");
if not v21 then
	v21 = Instance.new("BodyGyro");
	v21.P = 16000;
	v21.D = 120;
	v21.maxTorque = Vector3.new(6, -6, 6) * 1000;
	v21.cframe = l__Torso__4.CFrame;
	v21.Parent = l__Torso__4;
end;

function waitTime(p5)
	for i = 0, p5 do
		task.wait(0.03)
		if script.Parent.GamePause.Value then
			script.Parent.GamePause.Changed:Wait()
		end
	end
end;

function playSoundEffect(p2, p3)
	if script.Parent:FindFirstChild("SoundScript") then
		local v23 = Instance.new("StringValue");
		v23.Name = "Sound";
		v23.Value = p2;
		local v24 = Instance.new("ObjectValue");
		v24.Name = "Location";
		v24.Value = p3;
		v24.Parent = v23;
		v23.Parent = script.Parent.SoundScript.Effects;
	end;
end;
local l__CurrentCamera__1 = workspace.CurrentCamera;
l__Humanoid__3.Died:connect(function()
	checkDamage();
	coroutine.resume(coroutine.create(function()
		waitTime(4000);
		l__Value__1:Destroy();
		script:Destroy()
	end));
	waitTime(1);
	if l__Value__1:findFirstChild("Torso") and l__Torso__4.Position.y > 0 then
		local v25 = Instance.new("Explosion");
		v25.Position = l__Torso__4.Position;
		v25.BlastPressure = 0;
		v25.BlastRadius = 10;
		v25.Parent = l__CurrentCamera__1;
		l__Debris__2:AddItem(v25, 3);
		l__Value__1:BreakJoints();
		playSoundEffect("RoboticExplosion", l__Torso__4);
		if l__Stats__5.Counter.Value then
			l__Stats__5.Counter.Value.Value = l__Stats__5.Counter.Value.Value - 1;
		end;
	end;
end);
local u2 = false;
l__Humanoid__3.ChildAdded:connect(function()
	if l__Humanoid__3:findFirstChild("creator") and not u2 then
		u2 = true;
	end;
end);
l__Humanoid__3.ChildRemoved:connect(function()
	if not l__Humanoid__3:findFirstChild("creator") and u2 then
		u2 = false;
	end;
end);
local l__GameItems__3 = game.ReplicatedStorage.GameItems;
function visualDamage(p4, p5, p6)
	local v26 = Instance.new("BillboardGui");
	v26.Size = UDim2.new(1, 0, 1, 0);
	v26.StudsOffset = Vector3.new(math.random(-1, 1), 1.65, math.random(-1, 1));
	local v27 = l__GameItems__3.MasterGuis.DamageFrame:clone();
	v27.Parent = v26;
	if p5 == 0 then
		v27.TextLabel.Text = "-" .. p5;
		v27.TextLabel.TextStrokeColor3 = Color3.new(0, 0, 1);
	elseif p5 < 0 then
		v27.TextLabel.Text = "+" .. p5;
		v27.TextLabel.TextStrokeColor3 = Color3.new(0, 1, 0);
	else
		v27.TextLabel.Text = "-" .. p5;
		v27.TextLabel.TextStrokeColor3 = Color3.new(1, 0, 0);
	end;
	v26.Parent = p6;
	v26.Adornee = p6;
	local l__BillboardControl__28 = v27.BillboardControl;
	l__BillboardControl__28.Billboard.Value = v26;
	l__BillboardControl__28.Parent = script.Parent;
	l__BillboardControl__28.Disabled = false;
	l__Debris__2:AddItem(v26, 5);
end;
local function u4(p7)
	local l__X__29 = p7.Position.X;
	local l__Y__30 = p7.Position.Y;
	local l__Z__31 = p7.Position.Z;
	local l__X__32 = p7.Size.X;
	local l__Y__33 = p7.Size.Y;
	local l__Z__34 = p7.Size.Z;
	local v35 = p7.CFrame - p7.CFrame.p;
	p7:Destroy();
	local v36 = Instance.new("Part");
	v36.Name = "Averter";
	v36.FormFactor = 0;
	v36.Size = Vector3.new(1, 1, 1);
	v36.BrickColor = p7.BrickColor;
	v36.Shape = 1;
	v36.BottomSurface = 0;
	v36.TopSurface = 0;
	v36.Reflectance = p7.Reflectance;
	v36.Transparency = p7.Transparency;
	v36.CanCollide = false;
	for v37 = 0, l__X__32 - 1 do
		for v38 = 0, l__Y__33 - 1 do
			for v39 = 0, l__Z__34 - 1 do
				local v40 = v36:clone();
				v40.Velocity = Vector3.new(math.random(-20, 20), math.random(-20, 20), math.random(-20, 20));
				v40.CFrame = CFrame.new(l__X__29 - (l__X__32 - 1) / 2 + v37, l__Y__30 - (l__Y__33 - 1) / 2 + v38, l__Z__31 - (l__Z__34 - 1) / 2 + v39) * v35;
				l__Debris__2:AddItem(v40, 0.5);
				v40.Parent = l__CurrentCamera__1;
			end;
		end;
	end;
end;
function normalDamage(p8, p9)
	local v41 = p8.Parent:findFirstChild("Humanoid") or p8.Parent.Parent:findFirstChild("Humanoid");
	if v41 then
		if not game.Players:findFirstChild(v41.Parent.Name) then
			if v41.Parent:findFirstChild("MainControlVRT") then
				if 0 < v41.Health then
					if not v41.Parent:findFirstChild("ForceField") then
						if v41.Parent:findFirstChild("Head") then
							local v42 = math.ceil(p9 * playerStats.Difficulty.Value / 3);
							if p8.Name == "Head" then
								v42 = math.ceil(v42 * 2);
							elseif p8.Name == "Torso" then
								v42 = math.ceil(v42 * 1.5);
							end;
							v41:TakeDamage(v42);
							visualDamage(v41, v42, v41.Parent.Head);
							return;
						end;
					end;
				end;
			else
				if p8.Name == "Glass" then
					u4(p8);
					return;
				end;
				if p8.Name == "Explosive" then
					if p8:findFirstChild("Explode") then
						p8.Explode.Value = true;
					end;
				end;
			end;
		elseif 0 < v41.Health then
			if not v41.Parent:findFirstChild("ForceField") then
				if v41.Parent:findFirstChild("Head") then
					local v42 = math.ceil(p9 * playerStats.Difficulty.Value / 3);
					if p8.Name == "Head" then
						v42 = math.ceil(v42 * 2);
					elseif p8.Name == "Torso" then
						v42 = math.ceil(v42 * 1.5);
					end;
					v41:TakeDamage(v42);
					visualDamage(v41, v42, v41.Parent.Head);
					return;
				end;
			end;
		end;
	else
		if p8.Name == "Glass" then
			u4(p8);
			return;
		end;
		if p8.Name == "Explosive" then
			if p8:findFirstChild("Explode") then
				p8.Explode.Value = true;
			end;
		end;
	end;
end;
local v43 = Instance.new("Part");
v43.FormFactor = Enum.FormFactor.Custom;
v43.Size = Vector3.new(0.2, 0.2, 1);
v43.BrickColor = BrickColor.new("Bright red");
v43.CanCollide = false;
v43.Anchored = true;
v43.Transparency = 0.3;
v43.TopSurface = Enum.SurfaceType.Smooth;
v43.BottomSurface = Enum.SurfaceType.Smooth;
v43.Name = "Averter";
function RayIgnoreCheck(p10, p11)
	if p10 then
		if not (1 <= p10.Transparency) then
			if string.lower(p10.Name) ~= "water" then
				if p10.Name ~= "Effect" then
					if p10.Name ~= "Rocket" then
						if p10.Name ~= "Averter" then
							if p10.Parent.ClassName ~= "Hat" then
								if p10.Parent.ClassName == "Tool" then

								else
									return false;
								end;
							end;
						end;
					end;
				end;
			end;
		end;
	else
		return false;
	end;
	return true;
end;
function RayCast(p12, p13, p14)
	local v44, v45 = workspace:FindPartOnRay(Ray.new(p12 + p13 * 0.01, p13 * p14), l__Value__1);
	if v44 then
		if v45 then
			local v46 = p14 - (v45 - p12).magnitude;
			if RayIgnoreCheck(v44, v45) then
				if 0 < v46 then
					return RayCast(v45, p13, v46);
				end;
			end;
		end;
	end;
	return v44, v45;
end;
function laserBall(p15, p16)
	local v47 = Instance.new("Part");
	v47.Shape = "Block";
	v47.formFactor = "Symmetric";
	v47.Size = Vector3.new(1, 1, 1);
	v47.BrickColor = BrickColor.new("Bright red");
	v47.Transparency = 0.2;
	v47.TopSurface = 0;
	v47.BottomSurface = 0;
	v47.Locked = true;
	v47.Name = "Averter";
	v47.CFrame = CFrame.new(p15.CFrame * Vector3.new(4, 0, -0.5), p16.Position);
	v47.Parent = l__Value__1;
	local v48 = Instance.new("Weld");
	v48.Parent = p15;
	v48.Part0 = v48.Parent;
	v48.Part1 = v47;
	v48.C1 = CFrame.new(-4, 0, -0.5);
	playSoundEffect("LaserCharge", l__Torso__4);
	local v49 = Instance.new("SpecialMesh");
	v49.MeshType = "Sphere";
	v49.Scale = Vector3.new(0.1, 0.1, 0.1);
	v49.Parent = v47;
	local v50 = 1 - 1;
	while true do
		waitTime(2);
		v49.Scale = Vector3.new(0.2 * v50, 0.2 * v50, 0.2 * v50);
		if l__Humanoid__3.Health < 1 then
			v47:Destroy();
			return;
		end;
		move((time()));
		if 0 <= 1 then
			if v50 < 20 then

			else
				break;
			end;
		elseif 20 < v50 then

		else
			break;
		end;
		v50 = v50 + 1;	
	end;
	local v51 = Instance.new("Part");
	v51.Shape = "Block";
	v51.formFactor = "Symmetric";
	v51.Size = Vector3.new(2, 2, 2);
	v51.BrickColor = BrickColor.new("Bright red");
	v51.Transparency = 0.2;
	v51.TopSurface = 0;
	v51.BottomSurface = 0;
	v51.CanCollide = false;
	v51.Locked = true;
	v51.Name = "Averter";
	v51.CFrame = CFrame.new(p15.CFrame * Vector3.new(6, 0, -0.5), p16.Position);
	local v52 = Instance.new("SpecialMesh");
	v52.MeshType = "Sphere";
	v52.Scale = Vector3.new(1, 1, 1);
	v52.Parent = v51;
	local v53 = Instance.new("BodyVelocity");
	v53.velocity = (p16.Position + Vector3.new(math.random(-1, 1), 1, math.random(-1, 1)) - p15.CFrame.p).unit * 50;
	v53.Parent = v51;
	local v54 = Instance.new("BodyAngularVelocity");
	v54.angularvelocity = Vector3.new(math.random(-10, 10), math.random(-10, 10), math.random(-10, 10));
	v54.Parent = v51;
	v48.Parent = nil;
	v47:Destroy();
	playSoundEffect("LaserBlast", l__Torso__4);
	v51.Parent = l__CurrentCamera__1;
	v51.Touched:connect(function(p17)
		if p17 then
			if p17.Parent then
				if not p17:IsDescendantOf(l__Value__1) then
					normalDamage(p17, 20, "LaserBall");
					v51:Destroy();
				end;
			end;
		end;
	end);
end;
local u5 = l__Value__16 / 2;
local l__Head__6 = l__Value__1.Head;
function onFireNormal(p18, p19)
	if weaponMode == "EyeLaser" then
		local v55 = Instance.new("Part");
		v55.FormFactor = Enum.FormFactor.Symmetric;
		v55.Size = Vector3.new(1, 1, 1);
		v55.BrickColor = BrickColor.new("Bright red");
		v55.CanCollide = false;
		v55.Transparency = 0.3;
		v55.TopSurface = Enum.SurfaceType.Smooth;
		v55.BottomSurface = Enum.SurfaceType.Smooth;
		v55.Name = "Averter";
		local v56 = Instance.new("SpecialMesh");
		v56.MeshType = "Sphere";
		v56.Scale = Vector3.new(0, 0, 0);
		v56.Parent = v55;
		local v57 = Instance.new("Weld");
		v57.Parent = l__Value__1.Eye.Ring;
		v57.Part0 = l__Value__1.Eye.Ring;
		v57.Part1 = v55;
		v55.Parent = l__Value__1;
		v57.C1 = CFrame.new(v57.C1.p) + Vector3.new(0.2, 0, 1);
		playSoundEffect("LaserCharge", l__Torso__4);
		local v58 = 1 - 1;
		while true do
			waitTime(1);
			v56.Scale = Vector3.new(v58 * 0.12, v58 * 0.12, v58 * 0.12);
			move((time()));
			if 0 <= 1 then
				if v58 < 16 then

				else
					break;
				end;
			elseif 16 < v58 then

			else
				break;
			end;
			v58 = v58 + 1;		
		end;
		local v59 = 16 - -2;
		while true do
			waitTime(1);
			v56.Scale = Vector3.new(v59 * 0.12, v59 * 0.12, v59 * 0.12);
			move((time()));
			if 0 <= -2 then
				if v59 < 8 then

				else
					break;
				end;
			elseif 8 < v59 then

			else
				break;
			end;
			v59 = v59 + -2;		
		end;
		v57:Destroy();
		v55:Destroy();
	end;
	local v60 = (p19.Position - p18.Position).unit;
	if p19.Name ~= "Glass" then
		v60 = (CFrame.new(Vector3.new(0, 0, 0), v60) * CFrame.Angles(0, 0, math.random() * 2 * math.pi) * CFrame.Angles(math.random() * 0.2, 0, 0)).lookVector;
	end;
	local v61, v62 = RayCast(p18.Position, v60, u5);
	playSoundEffect("LaserShot", l__Torso__4);
	if v62 then
		local v63 = v43:clone();
		if weaponMode == "EyeLaser" then
			v63.Size = Vector3.new(0.5, 0.5, 1);
		end;
		local l__magnitude__64 = (v62 - p18.Position).magnitude;
		v63.CFrame = CFrame.new(v62, p18.Position) * CFrame.new(0, 0, -l__magnitude__64 / 2);
		local v65 = Instance.new("BlockMesh");
		v65.Scale = Vector3.new(1, 1, l__magnitude__64 - 2);
		v65.Offset = Vector3.new(0, 0, 2);
		v65.Parent = v63;
		v63.Parent = l__CurrentCamera__1;
		l__Debris__2:AddItem(v63, 0.06);
	end;
	if v61 then
		if v61.Parent then
			if v62 then
				local v66 = 4;
				if p18 == l__Head__6 then
					v66 = v66 * 1.5;
				end;
				normalDamage(v61, v66);
			end;
		end;
	end;
end;
local u7 = false;
local l__C1__8 = l__Weld__14.C1;
local l__C1__9 = l__Weld__13.C1;
local u10 = 0;
function checkAmmo()
	if l__Stats__5.Ammo.Value < 1 then
		u7 = true;
		l__Humanoid__3.WalkSpeed = 0;
		local v67, v68 = v6(l__Weld__14.C1, l__C1__8 * CFrame.Angles(0, 0, 1.5));
		local v69, v70 = v6(l__Weld__13.C1, l__C1__9 * CFrame.Angles(0, 0, 1.5));
		local v71 = 1 - 1;
		while true do
			l__Weld__14.C1 = v68(v71 / 30);
			l__Weld__13.C1 = v70(v71 / 30);
			waitTime(1);
			if 0 <= 1 then
				if v71 < 30 then

				else
					break;
				end;
			elseif 30 < v71 then

			else
				break;
			end;
			v71 = v71 + 1;		
		end;
		local v72 = 1 - 1;
		while true do
			l__Weld__13.C1 = l__Weld__13.C1 - Vector3.new(0, 0, 0.2);
			l__Weld__14.C1 = l__Weld__14.C1 - Vector3.new(0, 0, 0.2);
			waitTime(1);
			if 0 <= 1 then
				if v72 < 5 then

				else
					break;
				end;
			elseif 5 < v72 then

			else
				break;
			end;
			v72 = v72 + 1;		
		end;
		playSoundEffect("ElectronicReload", l__Head__6);
		local v73 = 1 - 1;
		while true do
			l__Weld__13.C1 = l__Weld__13.C1 + Vector3.new(0, 0, 0.2);
			l__Weld__14.C1 = l__Weld__14.C1 + Vector3.new(0, 0, 0.2);
			waitTime(1);
			if 0 <= 1 then
				if v73 < 5 then

				else
					break;
				end;
			elseif 5 < v73 then

			else
				break;
			end;
			v73 = v73 + 1;		
		end;
		u10 = 0;
		local v74, v75 = v6(l__Weld__14.C1, l__C1__8 * CFrame.Angles(0, 0, 0));
		local v76, v77 = v6(l__Weld__13.C1, l__C1__9 * CFrame.Angles(0, 0, 0));
		local v78 = 1 - 1;
		while true do
			l__Weld__14.C1 = v75(v78 / 30);
			l__Weld__13.C1 = v77(v78 / 30);
			waitTime(1);
			if 0 <= 1 then
				if v78 < 30 then

				else
					break;
				end;
			elseif 30 < v78 then

			else
				break;
			end;
			v78 = v78 + 1;		
		end;
		l__Stats__5.Ammo.Value = l__Stats__5.MaxAmmo.Value;
		l__Humanoid__3.WalkSpeed = l__Stats__5.Speed.Value;
		u7 = false;
	end;
end;
l__Stats__5.Ammo.Changed:connect(function()
	checkAmmo();
end);
local v79 = Instance.new("Part");
v79.Name = "Home";
v79.Transparency = 1;
v79.CanCollide = false;
v79.Anchored = true;
v79.CFrame = CFrame.new(l__Torso__4.Position);
v79.Parent = l__Value__1;
local u11 = "Pacing";
local u12 = 0;
function followEnemy(p20)
	if u7 then
		return;
	end;
	v21.cframe = CFrame.new(l__Torso__4.Position, (Vector3.new(p20.Position.x, l__Torso__4.Position.y, p20.Position.z)));
	local v80 = (l__Torso__4.Position.y - p20.Position.y) / (l__Torso__4.Position - p20.Position).magnitude;
	if 0.02 < math.abs(v80 - u10) then
		if u10 < v80 then
			v80 = u10 + 0.02;
		else
			v80 = u10 - 0.02;
		end;
	end;
	u10 = v80;
	l__Weld__13.C1 = l__C1__9 * CFrame.Angles(0, 0, -v80);
	l__Weld__14.C1 = l__C1__8 * CFrame.Angles(0, 0, -v80);
	local l__magnitude__81 = (p20.Position - l__Torso__4.Position).magnitude;
	if l__magnitude__81 < 10 then
		l__Humanoid__3.WalkSpeed = l__Stats__5.Speed.Value - (10 - l__magnitude__81) * (10 - l__magnitude__81) / (l__magnitude__81 * 100) * l__Stats__5.Speed.Value;
		if l__magnitude__81 < 5 then
			if u11 == "Pacing" then

			else
				return;
			end;
		else
			return;
		end;
	else
		l__Humanoid__3.WalkSpeed = l__Stats__5.Speed.Value;
		return;
	end;
	u12 = 0;
end;
function DirectionRayIgnoreCheck(p21, p22)
	if p21 then
		if p21.Name == "Glass" then

		elseif p21.Name == "Averter" then
			return true;
		else
			return false;
		end;
	else
		return false;
	end;
	if (p21.Position - l__Torso__4.Position).magnitude < u5 * 1.5 then
		if checkSight(p22) then
			onFireNormal(l__Head__6, p21);
		end;
	end;
	return true;
end;
function DirectionRayCast(p23, p24, p25)
	local v82, v83 = workspace:FindPartOnRay(Ray.new(p23, p24 * p25), l__Value__1);
	if v82 then
		if v83 then
			local v84 = p25 - (v83 - p23).magnitude;
			if DirectionRayIgnoreCheck(v82, v83) then
				if 0 < v84 then
					--return DirectionRayCast(v83, p24, v84);
				end;
			end;
		end;
	end;
	return v82, v83;
end;
function checkSight(p26)
	local v85 = Instance.new("Part");
	v85.Name = "Sight1";
	v85.Size = Vector3.new(1, 1, 1);
	v85.CanCollide = false;
	v85.Transparency = 1;
	local v86 = Instance.new("Weld");
	v86.Parent = l__Torso__4;
	v86.Part0 = l__Torso__4;
	v86.Part1 = v85;
	v86.C1 = v86.C1 + Vector3.new(16, 0, 12);
	v85.Parent = l__Value__1;
	local v87 = Instance.new("Part");
	v87.Name = "Sight2";
	v87.Size = Vector3.new(1, 1, 1);
	v87.CanCollide = false;
	v87.Transparency = 1;
	local v88 = Instance.new("Weld");
	v88.Parent = l__Torso__4;
	v88.Part0 = l__Torso__4;
	v88.Part1 = v87;
	v88.C1 = v88.C1 + Vector3.new(-16, 0, 12);
	v87.Parent = l__Value__1;
	local v89 = v85.Position - l__Torso__4.Position;
	local v90 = v87.Position - l__Torso__4.Position;
	local v91 = math.acos((v89.X * v90.X + v89.Y * v90.Y + v89.Z * v90.Z) / (v89.magnitude * v90.magnitude + 0.001));
	local v92 = Vector3.new(p26.X, 0, p26.Z) - l__Torso__4.Position;
	local v93 = v85.Position - l__Torso__4.Position;
	local v94 = math.acos((v92.X * v93.X + v92.Y * v93.Y + v92.Z * v93.Z) / (v92.magnitude * v93.magnitude + 0.001));
	local v95 = Vector3.new(p26.X, 0, p26.Z) - l__Torso__4.Position;
	local v96 = v87.Position - l__Torso__4.Position;
	local v97 = math.acos((v95.X * v96.X + v95.Y * v96.Y + v95.Z * v96.Z) / (v95.magnitude * v96.magnitude + 0.001));
	v85:Destroy();
	v86:Destroy();
	v87:Destroy();
	v88:Destroy();
	if v94 < v91 then
		if v97 < v91 then
			return true;
		end;
	end;
	return false;
end;
local u13 = nil;
local u14 = 0;
function enemyCounter()
	if u13 then
		u14 = u14 - 1;
		if u14 < -40 then
			u13 = nil;
			return;
		end;
		if u14 ~= 0 then
			if u14 ~= -10 then
				if u14 ~= -20 then
					if u14 == -30 then
						calculatePacing();
					end;
				else
					calculatePacing();
				end;
			else
				calculatePacing();
			end;
		else
			calculatePacing();
		end;
	end;
end;
function findNearestTorso(p27)
	local v98 = l__CurrentCamera__1:getChildren();
	if l__CurrentCamera__1:findFirstChild("Level") then
		if l__CurrentCamera__1.Level:findFirstChild("NPC") then
			local v99 = l__CurrentCamera__1.Level.NPC:getChildren();
			local v100 = #v99;
			local v101 = 1;
			while true do
				if v99[v101]:IsA("Model") then
					if v99[v101]:findFirstChild("Humanoid") then
						if v99[v101]:findFirstChild("MainControlVRT") then
							table.insert(v98, v99[v101]);
						end;
					end;
				end;
				if 0 <= 1 then
					if v101 < v100 then

					else
						break;
					end;
				elseif v100 < v101 then

				else
					break;
				end;
				v101 = v101 + 1;			
			end;
		end;
	end;
	local v102 = #v98;
	local v103 = 1 - 1;
	while true do
		if v98[v103] then
			if v98[v103]:IsA("Model") then
				if v98[v103] ~= l__Value__1 then
					local v104 = v98[v103]:findFirstChild("Torso");
					local v105 = v98[v103]:findFirstChild("Humanoid");
					if v104 then
						if v105 then
							if not v98[v103]:findFirstChild("MainControlNPC") then
								if (v104.Position - p27).magnitude <= l__Value__16 then
									if p27.Y - 48 < v104.Position.Y then
										if 0 < v105.Health then
											local v106, v107 = DirectionRayCast(p27, (v104.Position - p27).unit, l__Value__16);
											if v106 then
												if v106:IsDescendantOf(v98[v103]) then
													if u13 then
														if (v104.Position - p27).magnitude < (u13.Position - p27).magnitude then
															u14 = 10;
															u13 = v104;
														elseif v104 == u13 then
															u14 = 10;
														end;
													elseif not u2 then
														if (v104.Position - p27).magnitude < 4 then
															u14 = 10;
															u13 = v104;
														elseif checkSight(v107) then
															u14 = 10;
															u13 = v104;
														end;
													else
														u14 = 10;
														u13 = v104;
													end;
												else
													enemyCounter();
												end;
											else
												enemyCounter();
											end;
										end;
									end;
								end;
							end;
						end;
					end;
				end;
			end;
		end;
		if 0 <= 1 then
			if v103 < v102 then

			else
				break;
			end;
		elseif v102 < v103 then

		else
			break;
		end;
		v103 = v103 + 1;	
	end;
end;
chaingunRotation = 0;
chaingunRotationSpeed = 0;
weaponMode = "Chainguns";
weaponShots = 0;
local u15 = nil;
local l__C1__16 = l__Weld__15.C1;
local u17 = 0;
function enemyFound()
	u11 = "Following";
	if 0 <= u14 then
		u15 = u13;
	end;
	if not u7 then
		if weaponMode == "Chainguns" then
			chaingunRotation = chaingunRotation + 0.1 * chaingunRotationSpeed;
			if chaingunRotationSpeed < 4 then
				chaingunRotationSpeed = chaingunRotationSpeed + 0.1;
			end;
			if math.pi * 2 < chaingunRotation then
				chaingunRotation = chaingunRotation - math.pi * 2;
			end;
		else
			if 0 < chaingunRotationSpeed then
				chaingunRotationSpeed = chaingunRotationSpeed - 0.4;
			end;
			if l__Head__6.KeepSpin.IsPlaying then
				l__Head__6.KeepSpin:Stop();
				l__Head__6.StopSpin:Play();
			end;
		end;
	else
		if 0 < chaingunRotationSpeed then
			chaingunRotationSpeed = chaingunRotationSpeed - 0.4;
		end;
		if l__Head__6.KeepSpin.IsPlaying then
			l__Head__6.KeepSpin:Stop();
			l__Head__6.StopSpin:Play();
		end;
	end;
	l__Weld__15.C1 = l__C1__16 * CFrame.Angles(chaingunRotation, 0, 0);
	if 3 < u17 then
		if (u13.Position - l__Torso__4.Position).magnitude < u5 then
			if 0 < l__Stats__5.Ammo.Value then
				if checkSight(u13.Position) then
					if weaponShots <= 0 then
						if l__Torso__4.Position.y + 2 < u13.Position.y then
							weaponMode = "UpperGuns";
						else
							local v108 = math.random(0, 20);
							if v108 == 0 then
								weaponMode = "None";
							elseif v108 < 7 then
								if l__Value__1:findFirstChild("LeftArm") then
									weaponMode = "Cannons";
									weaponShots = 2;
								else
									weaponMode = "EyeLaser";
								end;
							elseif v108 < 11 then
								weaponMode = "UpperGuns";
								weaponShots = 10;
							elseif l__Value__1:findFirstChild("RightArm") then
								weaponMode = "Chainguns";
								weaponShots = 20;
								l__Head__6.StartSpin:Play();
								coroutine.resume(coroutine.create(function()
									wait(l__Head__6.StartSpin.TimeLength - 0.02);
									l__Head__6.KeepSpin:Play();
								end));
							else
								weaponMode = "EyeLaser";
							end;
						end;
						if weaponMode ~= "Chainguns" then
							if l__Head__6.KeepSpin.IsPlaying then
								l__Head__6.KeepSpin:Stop();
								l__Head__6.StopSpin:Play();
							end;
						end;
					end;
					if weaponMode == "Chainguns" then
						if 4 <= chaingunRotationSpeed then
							if l__Value__1:findFirstChild("RightArm") then
								onFireNormal(l__Value__1.RightArm.Hand["Chaingun" .. math.random(1, 3)], u13);
								l__Stats__5.Ammo.Value = l__Stats__5.Ammo.Value - 1;
								if l__Stats__5.Ammo.Value < 1 then
									weaponShots = 0;
								else
									weaponShots = weaponShots - 1;
								end;
								u17 = 1;
								return;
							else
								weaponShots = 0;
								return;
							end;
						end;
					end;
					if weaponMode == "Cannons" then
						if l__Value__1:findFirstChild("LeftArm") then
							laserBall(l__Value__1.LeftArm["Launcher" .. weaponShots], u13);
							l__Stats__5.Ammo.Value = l__Stats__5.Ammo.Value - 4;
							if l__Stats__5.Ammo.Value < 1 then
								weaponShots = 0;
							else
								weaponShots = weaponShots - 1;
							end;
							u17 = -1;
							return;
						else
							weaponShots = 0;
							return;
						end;
					end;
					if weaponMode == "UpperGuns" then
						onFireNormal(l__Value__1.Main["Chaingun" .. math.random(1, 3)], u13);
						l__Stats__5.Ammo.Value = l__Stats__5.Ammo.Value - 1;
						if l__Stats__5.Ammo.Value < 1 then
							weaponShots = 0;
						else
							weaponShots = weaponShots - 1;
						end;
						u17 = -1;
						return;
					else
						if weaponMode == "None" then
							u17 = 0;
							return;
						end;
						if weaponMode == "EyeLaser" then
							onFireNormal(l__Value__1.Eye.Ring, u13);
							u17 = 0;
							return;
						end;
					end;
				elseif l__Value__16 < (u13.Position - l__Torso__4.Position).magnitude then
					enemyCounter();
				end;
			elseif l__Value__16 < (u13.Position - l__Torso__4.Position).magnitude then
				enemyCounter();
			end;
		elseif l__Value__16 < (u13.Position - l__Torso__4.Position).magnitude then
			enemyCounter();
		end;
	elseif l__Value__16 < (u13.Position - l__Torso__4.Position).magnitude then
		enemyCounter();
	end;
end;
function calculatePacing()
	if not u13 then
		if v19 then
			v79.CFrame = CFrame.new(v20[l__Path__18.Value].Value);
			l__Path__18.Value = l__Path__18.Value + 1;
			if #v20 < l__Path__18.Value then
				l__Path__18.Value = 1;
			end;
		else
			v79.CFrame = CFrame.new(l__Torso__4.Position) + Vector3.new(math.random(-30, 30), 0, math.random(-30, 30));
		end;
	else
		v79.CFrame = CFrame.new(u13.Position) + Vector3.new(12 * (math.random(0, 1) * 2 - 1), 0, 12 * (math.random(0, 1) * 2 - 1));
	end;
	u15 = v79;
	local v109, v110 = DirectionRayCast(l__Torso__4.Position, (v79.Position - l__Torso__4.Position).unit, l__Value__16);
	if (v110 - l__Torso__4.Position).magnitude < (v79.CFrame.p - l__Torso__4.Position).magnitude then
		v79.CFrame = CFrame.new(v110);
	end;
end;
function enemyLost()
	if u12 <= 0 then

	else
		u12 = u12 - 1;
		return;
	end;
	u11 = "Pacing";
	u12 = 200;
	calculatePacing();
end;
l__Stats__5.EnemyFound.Changed:connect(function()
	if not l__Stats__5.EnemyFound.Value then
		u12 = 80;
		u11 = "Standing";
		u15 = nil;
		enemyLost();
	end;
end);
local u18 = nil;
local u19 = nil;
function checkDamage()
	local function v111(p28)
		local v112 = Instance.new("Explosion");
		v112.Position = p28.Main.Position;
		v112.BlastPressure = 0;
		v112.BlastRadius = 5;
		v112.Parent = l__CurrentCamera__1;
		l__Debris__2:AddItem(v112, 1);
		p28:BreakJoints();
		p28.Name = "Broken";
		playSoundEffect("RoboticExplosion", l__Torso__4);
		local function u20(p29)
			local v113 = p29:GetChildren();
			local v114 = #v113;
			local v115 = 1 - 1;
			while true do
				if v113[v115] then
					if v113[v115]:IsA("Part") then
						v113[v115].Velocity = Vector3.new(math.random(-20, 20), math.random(-20, 20), math.random(-20, 20));
					elseif v113[v115] then
						if v113[v115]:IsA("Model") then
							u20(v113[v115]);
						end;
					end;
				elseif v113[v115] then
					if v113[v115]:IsA("Model") then
						u20(v113[v115]);
					end;
				end;
				if 0 <= 1 then
					if v115 < v114 then

					else
						break;
					end;
				elseif v114 < v115 then

				else
					break;
				end;
				v115 = v115 + 1;			
			end;
		end;
		u20(p28);
		if l__CurrentCamera__1:findFirstChild("Level") then
			if l__CurrentCamera__1.Level:findFirstChild("Tool") then
				if p28:findFirstChild("Hand") then
					local v116 = 1;
					while true do
						local v117 = p28.Hand["Chaingun" .. v116];
						v117.Name = "Chaingun";
						v117.CanCollide = true;
						coroutine.resume(coroutine.create(function()
							while true do
								wait(0.09);
								if not (v117.Velocity.magnitude < 0.1) then

								else
									break;
								end;							
							end;
							v117.Anchored = true;
						end));
						v117.Parent = l__CurrentCamera__1.Level.Tool;
						if 0 <= 1 then
							if v116 < 3 then

							else
								break;
							end;
						elseif 3 < v116 then

						else
							break;
						end;
						v116 = v116 + 1;					
					end;
				end;
			end;
		end;
	end;
	if l__Humanoid__3.MaxHealth / 4 <= l__Humanoid__3.Health then
		if l__Humanoid__3.Health < l__Humanoid__3.MaxHealth / 2 then
			if v17 == 1 then
				if l__Value__1:findFirstChild("RightArm") then
					v111(l__Value__1.RightArm);
				elseif v17 == 0 then
					if l__Value__1:findFirstChild("LeftArm") then
						v111(l__Value__1.LeftArm);
					end;
				end;
			elseif v17 == 0 then
				if l__Value__1:findFirstChild("LeftArm") then
					v111(l__Value__1.LeftArm);
				end;
			end;
			if not u18 then
				u18 = Instance.new("Smoke");
				u18.Color = Color3.new(0.3176470588235294, 0.3176470588235294, 0.3176470588235294);
				u18.Opacity = 0.2;
				u18.Size = 0.1;
				u18.Parent = l__Value__1.Main.RightShoulder;
				return;
			end;
		elseif l__Humanoid__3.Health < l__Humanoid__3.MaxHealth / 4 then
			if v17 == 0 then
				if l__Value__1:findFirstChild("RightArm") then
					v111(l__Value__1.RightArm);
				elseif v17 == 1 then
					if l__Value__1:findFirstChild("LeftArm") then
						v111(l__Value__1.LeftArm);
					end;
				end;
			elseif v17 == 1 then
				if l__Value__1:findFirstChild("LeftArm") then
					v111(l__Value__1.LeftArm);
				end;
			end;
			if not u19 then
				u19 = Instance.new("Smoke");
				u19.Color = Color3.new(0.3176470588235294, 0.3176470588235294, 0.3176470588235294);
				u19.Opacity = 0.2;
				u19.Size = 0.1;
				u19.Parent = l__Value__1.Main.LeftShoulder;
			end;
		end;
	elseif l__Humanoid__3.Health < l__Humanoid__3.MaxHealth / 4 then
		if v17 == 0 then
			if l__Value__1:findFirstChild("RightArm") then
				v111(l__Value__1.RightArm);
			elseif v17 == 1 then
				if l__Value__1:findFirstChild("LeftArm") then
					v111(l__Value__1.LeftArm);
				end;
			end;
		elseif v17 == 1 then
			if l__Value__1:findFirstChild("LeftArm") then
				v111(l__Value__1.LeftArm);
			end;
		end;
		if not u19 then
			u19 = Instance.new("Smoke");
			u19.Color = Color3.new(0.3176470588235294, 0.3176470588235294, 0.3176470588235294);
			u19.Opacity = 0.2;
			u19.Size = 0.1;
			u19.Parent = l__Value__1.Main.LeftShoulder;
		end;
	end;
end;
local u21 = l__Stats__5.OffsetMaxX.Value + l__Torso__4.Position.X;
local u22 = l__Stats__5.OffsetMaxZ.Value + l__Torso__4.Position.Z;
local u23 = l__Stats__5.OffsetMinX.Value + l__Torso__4.Position.X;
local u24 = l__Stats__5.OffsetMinZ.Value + l__Torso__4.Position.Z;
local u25 = 0;
local u26 = "RightBackward";
local u27 = 0;
local u28 = 0;
local u29 = false;
local l__C1__30 = l__Weld__7.C1;
local l__C1__31 = l__Weld__8.C1;
local l__C1__32 = l__Weld__9.C1;
local l__C1__33 = l__Weld__10.C1;
local l__C1__34 = l__Weld__11.C1;
local l__C1__35 = l__Weld__12.C1;
function move(p30)
	local v118, v119
	
	if u11 ~= "Standing" then
		if not u7 then
			v118 = 0.5;
			v119 = 4;
		else
			v118 = 0;
			v119 = 0;
		end;
	else
		v118 = 0;
		v119 = 0;
	end;
	local v120 = v118 * math.sin(p30 * v119);
	if 0.05 < math.abs(v120 - u25) then
		if u25 < v120 then
			v120 = u25 + 0.05;
		else
			v120 = u25 - 0.05;
		end;
	end;
	if u25 < v120 then
		if u26 == "RightForward" then
			u26 = "RightBackward";
			u27 = -v120 * 1.5 - 0.1;
			u28 = 0;
			u29 = false;
		elseif v120 < u25 then
			if u26 == "RightBackward" then
				u26 = "RightForward";
				u27 = v120 * 1.5 - 0.1;
				u28 = 0;
				u29 = false;
			end;
		end;
	elseif v120 < u25 then
		if u26 == "RightBackward" then
			u26 = "RightForward";
			u27 = v120 * 1.5 - 0.1;
			u28 = 0;
			u29 = false;
		end;
	end;
	u25 = v120;
	l__Weld__7.C1 = l__C1__30 * CFrame.Angles(0, 0, -v120 - 0.2);
	l__Weld__8.C1 = l__C1__31 * CFrame.Angles(0, 0, v120 - 0.2);
	local v121 = 0;
	local v122 = 0;
	if 0 < v120 then
		v122 = v120;
	else
		v121 = v120;
	end;
	l__Weld__9.C1 = l__C1__32 * CFrame.Angles(0, 0, -v120 / 1.4 + v122 * 1.5);
	l__Weld__10.C1 = l__C1__33 * CFrame.Angles(0, 0, v120 / 1.4 - v121 * 1.5);
	if 0 < u27 then
		u27 = u27 - 0.05;
	end;
	local v123 = v120;
	if 0.1 < math.abs(v123 - u28) then
		if u28 < v123 then
			v123 = u28 + 0.1;
		else
			v123 = u28 - 0.1;
		end;
	end;
	if u26 == "RightForward" then
		l__Weld__11.C1 = l__C1__34 * CFrame.Angles(0, 0, u27 - v122 * 1.5);
		l__Weld__12.C1 = l__C1__35 * CFrame.Angles(0, 0, -v123 * 1.5 - 0.1 + v121 * 1.5);
		if -v123 < -0.2 then
			if not u7 then
				if not u29 then
					playSoundEffect("MetalStomp", l__Value__1.LeftLeg.Foot.Main);
					u29 = true;
				end;
			end;
		end;
	else
		l__Weld__11.C1 = l__C1__34 * CFrame.Angles(0, 0, v123 * 1.5 - 0.1 - v122 * 1.5);
		l__Weld__12.C1 = l__C1__35 * CFrame.Angles(0, 0, u27 + v121 * 1.5);
		if v123 < -0.2 then
			if not u7 then
				if not u29 then
					playSoundEffect("MetalStomp", l__Value__1.RightLeg.Foot.Main);
					u29 = true;
				end;
			end;
		end;
	end;
	u28 = v123;
end;
local u36 = 0;
local function u37(p31)
	local v129
	if u21 < l__Torso__4.Position.X or u22 < l__Torso__4.Position.Z or l__Torso__4.Position.X < u23 or l__Torso__4.Position.Z < u24 then
		v79.CFrame = CFrame.new((u21 + u23) / 2, l__Torso__4.Position.Y, (u22 + u24) / 2);
		p31 = v79;
		u12 = 200;
		local v124, v125 = DirectionRayCast(l__Torso__4.Position, (v79.Position - l__Torso__4.Position).unit, l__Value__16);
		if v124 then
			wait();
			if math.random(1, 2) % 2 then
				local v126 = (u22 + u24) / 2;
				v79.CFrame = CFrame.new(l__Torso__4.Position.X, l__Torso__4.Position.Y, math.random(v126 - 4, v126 + 4));
				p31 = v79;
				local v127, v128 = DirectionRayCast(l__Torso__4.Position, (v79.Position - l__Torso__4.Position).unit, l__Value__16);
				v129 = v127;
			else
				local v130 = (u21 + u23) / 2;
				v79.CFrame = CFrame.new(math.random(v130 - 4, v130 + 4), l__Torso__4.Position.Y, l__Torso__4.Position.Z);
				p31 = v79;
				local v131, v132 = DirectionRayCast(l__Torso__4.Position, (v79.Position - l__Torso__4.Position).unit, l__Value__16);
				v129 = v131;
			end;
			if v129 then
				v79.CFrame = CFrame.new((u21 + u23) / 2, l__Torso__4.Position.Y, (u22 + u24) / 2);
				p31 = v79;
			end;
		end;
	end;
	l__Humanoid__3:MoveTo(p31.Position, p31);
end;
function runBot(p32)
	move(p32);
	if 0 < l__Humanoid__3.Health then
		local v133 = nil;
		u36 = u36 + 1;
		if u36 == 10 then
			u36 = 0;
			findNearestTorso(l__Torso__4.Position);
		end;
		if u13 then
			l__Stats__5.State.Value = 2;
			l__Stats__5.EnemyFound.Value = true;
			enemyFound();
		else
			l__Stats__5.State.Value = 1;
			if l__Stats__5.EnemyFound.Value then
				l__Stats__5.EnemyFound.Value = false;
			else
				enemyLost();
			end;
		end;
		if u15 then
			u37(u15);
			followEnemy(u15);
		else
			u37(l__Torso__4);
		end;
		checkDamage();
		local v134, v135, v136 = l__Torso__4.CFrame:toEulerAnglesXYZ();
		local v133 = math.deg(v135 + math.pi / 2);
		
		local v137
		
		if 0 < l__Torso__4.CFrame.lookVector.Z then
			v137 = v133 + 180;
		else
			v137 = 180 - v133;
		end;
		l__Stats__5.RadarRotation.Value = math.ceil(v137 + 180);
	else
		if u18 then
			u18:Destroy();
		end;
		if u19 then
			u19:Destroy();
		end;
		u11 = "Standing";
		u15 = nil;
	end;
	u17 = u17 + 1;
end;
checkAmmo();
wait(l__Stats__5.WaitTime.Value);
while l__Value__1 do
	local v138, v139 = wait();
	if script.Parent:findFirstChild("LocalScript") and script.Parent.LocalScript:findFirstChild("LocalPause") then
		if not script.Parent.LocalScript.LocalPause.Value then
			if l__Humanoid__3.WalkSpeed == 0 and l__Humanoid__3.Health > 0 and not u7 then
				l__Humanoid__3.WalkSpeed = l__Stats__5.Speed.Value;
			end;
			runBot(v139);
		elseif l__Humanoid__3.WalkSpeed ~= 0 then
			l__Humanoid__3.WalkSpeed = 0;
		end;
	else
		runBot(v139);
	end;
end;
