-- Decompiled with the Synapse X Luau decompiler.

local u1 = nil;
local u2 = nil;

print("Running Griever Script");

local l__Value__1 = script.LinkedModel.Value;
local l__Debris__2 = game:GetService("Debris");
local l__Humanoid__3 = l__Value__1.Humanoid;

game:GetService("ScriptContext").Error:Connect(function(Error, trace, erroredScript)
	if erroredScript == script then
		warn("Error generated by: " .. l__Humanoid__3.Parent.Name)
		warn(Error)
	end
end)

local l__Torso__4 = l__Value__1.Torso;
local l__Head__5 = l__Value__1.Head;
local l__Stats__6 = l__Value__1.Stats;
playerStats = game.Players.LocalPlayer.Stats
l__Humanoid__3.MaxHealth = l__Stats__6.Health.Value * (playerStats.Difficulty.Value / 3);
l__Humanoid__3.Health = l__Humanoid__3.MaxHealth;
l__Humanoid__3.WalkSpeed = l__Stats__6.Speed.Value;
local l__Value__7 = l__Stats__6.Authority.Value;
local l__Value__8 = l__Stats__6.Range.Value;
local v9 = math.random(0, 1);
local l__Path__10 = l__Stats__6.Path;
local v11 = false;
local v12 = l__Path__10:GetChildren();
if #v12 > 0 then
	v11 = true;
end;
function unanchor(p1)
	local v13 = p1:GetChildren();
	local v14 = #v13;
	local v15 = 1 - 1;
	while true do
		if v13[v15] then
			if v13[v15]:IsA("Part") then
				v13[v15].Anchored = false;
			elseif v13[v15] then
				if v13[v15]:IsA("Model") then
					unanchor(v13[v15]);
				end;
			end;
		elseif v13[v15] then
			if v13[v15]:IsA("Model") then
				unanchor(v13[v15]);
			end;
		end;
		if 0 <= 1 then
			if v15 < v14 then

			else
				break;
			end;
		elseif v14 < v15 then

		else
			break;
		end;
		v15 = v15 + 1;	
	end;
end;
unanchor(l__Value__1);

u2 = l__Value__1;
u1 = l__Torso__4;

for i = 1, 5 do
	task.spawn(function()
		print("Creating tail part " .. tostring(i))
		local v17 = u2["TailPart" .. i];
		local v18 = u1;
		local v19 = 3;
		v17.CFrame = u1.CFrame;
		v17.CanCollide = false;
		if i == 2 then
			v18 = u2.TailPart1;
			v19 = 1.8;
		elseif i == 3 then
			v18 = u2.TailPart2;
			v19 = 1.6;
		elseif i == 4 then
			v18 = u2.TailPart3;
			v19 = 1.2;
		elseif i == 5 then
			v18 = u2.TailPart4;
			v19 = 1;
		end;
		local v20 = Instance.new("BodyPosition");
		v20.maxForce = Vector3.new(1, 1, 1) * 150000;
		v20.position = v17.Position;
		v20.Parent = v17;
		local v21 = Instance.new("BodyGyro");
		v21.maxTorque = Vector3.new(1, 1, 1) * 60000;
		v21.Parent = v17;
		while true do
			wait(0.1);
			if v19 + 0.1 < (v17.Position - v18.Position).magnitude then
				local l__unit__22 = (v18.Position - v17.Position).unit;
				v20.position = v18.Position - (l__unit__22 * Vector3.new(1, 0, 1)).unit * v19;
				if v18.Name == "TailConnectorPart" then
					v21.cframe = CFrame.new(Vector3.new(0, 0, 0), v18.Position + Vector3.new(0, -2.5, 0) - v17.Position);
				else
					v21.cframe = CFrame.new(Vector3.new(0, 0, 0), l__unit__22);
				end;
			end;		
		end;
	end)
end

print("Finished creating tail parts.")

local v23 = Instance.new("BodyGyro");
v23.maxTorque = Vector3.new(4000000000000, 0, 4000000000000);
v23.P = 10000;
v23.D = 400;
v23.Parent = u1;


function waitTime(p5)
	for i = 0, p5 do
		task.wait(0.03)
		if script.Parent.GamePause.Value then
			script.Parent.GamePause.Changed:Wait()
		end
	end
end;

local l__CurrentCamera__4 = workspace.CurrentCamera;
local function u5(p3)
	local l__X__25 = p3.Position.X;
	local l__Y__26 = p3.Position.Y;
	local l__Z__27 = p3.Position.Z;
	local l__X__28 = p3.Size.X;
	local l__Y__29 = p3.Size.Y;
	local l__Z__30 = p3.Size.Z;
	local v31 = p3.CFrame - p3.CFrame.p;
	p3:Destroy();
	local v32 = Instance.new("Part");
	v32.Name = "Averter";
	v32.FormFactor = 0;
	v32.Size = Vector3.new(1, 1, 1);
	v32.BrickColor = p3.BrickColor;
	v32.Shape = 1;
	v32.BottomSurface = 0;
	v32.TopSurface = 0;
	v32.Reflectance = p3.Reflectance;
	v32.Transparency = p3.Transparency;
	v32.CanCollide = false;
	for v33 = 0, l__X__28 - 1 do
		for v34 = 0, l__Y__29 - 1 do
			for v35 = 0, l__Z__30 - 1 do
				local v36 = v32:clone();
				v36.Velocity = Vector3.new(math.random(-20, 20), math.random(-20, 20), math.random(-20, 20));
				v36.CFrame = CFrame.new(l__X__25 - (l__X__28 - 1) / 2 + v33, l__Y__26 - (l__Y__29 - 1) / 2 + v34, l__Z__27 - (l__Z__30 - 1) / 2 + v35) * v31;
				l__Debris__2:AddItem(v36, 0.5);
				v36.Parent = l__CurrentCamera__4;
			end;
		end;
	end;
end;
local l__GameItems__6 = game.ReplicatedStorage.GameItems;
function visualDamage(p4, p5, p6)
	local v37 = Instance.new("BillboardGui");
	v37.Size = UDim2.new(1, 0, 1, 0);
	v37.StudsOffset = Vector3.new(math.random(-1, 1), 1.65, math.random(-1, 1));
	local v38 = l__GameItems__6.MasterGuis.DamageFrame:clone();
	v38.Parent = v37;
	if p5 == 0 then
		v38.TextLabel.Text = "-" .. p5;
		v38.TextLabel.TextStrokeColor3 = Color3.new(0, 0, 1);
	elseif p5 < 0 then
		v38.TextLabel.Text = "+" .. p5;
		v38.TextLabel.TextStrokeColor3 = Color3.new(0, 1, 0);
	else
		v38.TextLabel.Text = "-" .. p5;
		v38.TextLabel.TextStrokeColor3 = Color3.new(1, 0, 0);
	end;
	v37.Parent = p6;
	v37.Adornee = p6;
	local l__BillboardControl__39 = v38.BillboardControl;
	l__BillboardControl__39.Billboard.Value = v37;
	l__BillboardControl__39.Parent = script.Parent;
	l__BillboardControl__39.Disabled = false;
	l__Debris__2:AddItem(v37, 5);
end;
function normalDamage(p7, p8)
	local v40 = p7.Parent:findFirstChild("Humanoid") or p7.Parent.Parent:findFirstChild("Humanoid");
	if v40 then
		if not game.Players:findFirstChild(v40.Parent.Name) then
			if v40.Parent:findFirstChild("MainControlVRT") then
				if 0 < v40.Health then
					if not v40.Parent:findFirstChild("ForceField") then
						if v40.Parent:findFirstChild("Head") then
							local v41 = math.ceil(p8 * playerStats.Difficulty.Value / 3);
							if p7.Name == "Head" then
								v41 = math.ceil(v41 * 2);
							elseif p7.Name == "Torso" then
								v41 = math.ceil(v41 * 1.5);
							end;
							v40:TakeDamage(v41);
							visualDamage(v40, v41, v40.Parent.Head);
							return;
						end;
					end;
				end;
			else
				if p7.Name == "Glass" then
					u5(p7);
					return;
				end;
				if p7.Name == "Explosive" then
					if p7:findFirstChild("Explode") then
						p7.Explode.Value = true;
					end;
				end;
			end;
		elseif 0 < v40.Health then
			if not v40.Parent:findFirstChild("ForceField") then
				if v40.Parent:findFirstChild("Head") then
					v41 = math.ceil(p8 * playerStats.Difficulty.Value / 3);
					if p7.Name == "Head" then
						v41 = math.ceil(v41 * 2);
					elseif p7.Name == "Torso" then
						v41 = math.ceil(v41 * 1.5);
					end;
					v40:TakeDamage(v41);
					visualDamage(v40, v41, v40.Parent.Head);
					return;
				end;
			end;
		end;
	else
		if p7.Name == "Glass" then
			u5(p7);
			return;
		end;
		if p7.Name == "Explosive" then
			if p7:findFirstChild("Explode") then
				p7.Explode.Value = true;
			end;
		end;
	end;
end;
local u7 = false;
function onFireNormal(p9, p10)
	u7 = true;
	local v42 = Instance.new("Part");
	v42.Shape = "Block";
	v42.formFactor = "Symmetric";
	v42.Size = Vector3.new(1, 1, 1);
	v42.BrickColor = BrickColor.new("Bright red");
	v42.Transparency = 0.2;
	v42.TopSurface = 0;
	v42.BottomSurface = 0;
	v42.Locked = true;
	v42.Name = "Averter";
	v42.CFrame = CFrame.new(p9.CFrame * Vector3.new(0, 1, -3), p10.Position);
	v42.Parent = u2;
	local v43 = Instance.new("Weld");
	v43.Parent = p9;
	v43.Part0 = v43.Parent;
	v43.Part1 = v42;
	v43.C1 = CFrame.new(0, 0, 3);
	if script.Parent:FindFirstChild("SoundScript") then
		local v44 = Instance.new("StringValue");
		v44.Name = "Sound";
		v44.Value = "LaserCharge";
		local v45 = Instance.new("ObjectValue");
		v45.Name = "Location";
		v45.Value = u1;
		v45.Parent = v44;
		v44.Parent = script.Parent.SoundScript.Effects;
	end;
	local v46 = Instance.new("SpecialMesh");
	v46.MeshType = "Sphere";
	v46.Scale = Vector3.new(0.1, 0.1, 0.1);
	v46.Parent = v42;
	local v47 = 1 - 1;
	while true do
		wait(0.05);
		v46.Scale = Vector3.new(0.2 * v47, 0.2 * v47, 0.2 * v47);
		v43.C1 = v43.C1 + Vector3.new(0, -0.1, 0);
		if l__Humanoid__3.Health < 1 then
			v42:Destroy();
			return;
		end;
		if 0 <= 1 then
			if v47 < 20 then

			else
				break;
			end;
		elseif 20 < v47 then

		else
			break;
		end;
		v47 = v47 + 1;	
	end;
	local v48 = Instance.new("Part");
	v48.Shape = "Block";
	v48.formFactor = "Symmetric";
	v48.Size = Vector3.new(2, 2, 2);
	v48.BrickColor = BrickColor.new("Bright red");
	v48.Transparency = 0.2;
	v48.TopSurface = 0;
	v48.BottomSurface = 0;
	v48.CanCollide = false;
	v48.Locked = true;
	v48.Name = "Averter";
	v48.CFrame = CFrame.new(p9.CFrame * Vector3.new(0, 2, -5), p10.Position);
	local v49 = Instance.new("SpecialMesh");
	v49.MeshType = "Sphere";
	v49.Scale = Vector3.new(1, 1, 1);
	v49.Parent = v48;
	local v50 = Instance.new("BodyVelocity");
	v50.velocity = p9.CFrame.lookVector * 50;
	v50.Parent = v48;
	local v51 = Instance.new("BodyAngularVelocity");
	v51.angularvelocity = Vector3.new(math.random(-1, 1), math.random(-1, 1), math.random(-1, 1));
	v51.Parent = v48;
	v43.Parent = nil;
	v42:Destroy();
	if script.Parent:FindFirstChild("SoundScript") then
		local v52 = Instance.new("StringValue");
		v52.Name = "Sound";
		v52.Value = "LaserBlast";
		local v53 = Instance.new("ObjectValue");
		v53.Name = "Location";
		v53.Value = u1;
		v53.Parent = v52;
		v52.Parent = script.Parent.SoundScript.Effects;
	end;
	v48.Parent = l__CurrentCamera__4;
	v48.Touched:Connect(function(p11)
		if p11 then
			if p11.Parent then
				normalDamage(p11, 20, l__Stats__6.Tool.Value);
				v48:Destroy();
			end;
		end;
	end);
	wait(0.1);
	if p9:findFirstChild("LaserCharge") then
		p9.LaserCharge:Stop();
	end;
	
	waitTime(10);

	u7 = false;
end;
l__Humanoid__3.Died:connect(function()
	coroutine.resume(coroutine.create(function()
		waitTime(400);
		u2:Destroy();
		script:Destroy()
	end));
	waitTime(1);
	if u2:findFirstChild("Torso") and u1.Position.y > -20 then
		local v54 = Instance.new("Explosion");
		v54.Position = u1.Position;
		v54.BlastPressure = 0;
		v54.BlastRadius = 5;
		v54.Parent = l__CurrentCamera__4;
		l__Debris__2:AddItem(v54, 3);
		u2:BreakJoints();
		local v55 = script.Parent:FindFirstChild("SoundScript");
		if v55 then
			v55 = Instance.new("StringValue");
			v55.Name = "Sound";
			v55.Value = "RoboticExplosion";
			local v56 = Instance.new("ObjectValue");
			v56.Name = "Location";
			v56.Value = u1;
			v56.Parent = v55;
			v55.Parent = script.Parent.SoundScript.Effects;
		end;
		local function u8(p12)
			local v57 = p12:GetChildren();
			for v58 = 1, #v57 do
				if v57[v58] and v57[v58]:IsA("Part") then
					v57[v58].Velocity = Vector3.new(math.random(-20, 20), math.random(-20, 20), math.random(-20, 20));
				elseif v57[v58] and v57[v58]:IsA("Model") then
					u8(v57[v58]);
				end;
			end;
		end;
		u8(u2);
		if l__CurrentCamera__4:findFirstChild("Level") and l__CurrentCamera__4.Level:findFirstChild("Tool") and l__GameItems__6.MasterTools:findFirstChild(l__Stats__6.Tool.Value) then
			local v59 = l__GameItems__6.MasterTools[l__Stats__6.Tool.Value]:clone();
			v59.CanCollide = true;
			v59.CFrame = u1.CFrame;
			coroutine.resume(coroutine.create(function()
				while true do
					wait(0.09);
					if v59.Velocity.magnitude < 0.1 then
						break;
					end;				
				end;
				v59.Anchored = true;
			end));
			v59.Parent = l__CurrentCamera__4.Level.Tool;
			v59.Velocity = Vector3.new(math.random(-20, 20), math.random(-20, 20), math.random(-20, 20));
		end;
		if l__Stats__6.Counter.Value then
			l__Stats__6.Counter.Value.Value = l__Stats__6.Counter.Value.Value - 1;
		end;
		--script.LinkedModel.Value = nil;
		--waitTime(500);
		--script:Destroy();
	end;
end);
local u9 = false;
u1.Touched:connect(function(p13)
	if p13 and p13.Parent and p13.Transparency < 1 and p13.CanCollide then
		local v60 = p13.Parent:findFirstChild("Humanoid") or p13.Parent.Parent:findFirstChild("Humanoid");
		if v60 then
			if v60.Health > 0 and not v60.Parent:findFirstChild("MainControlNPC") then
				u9 = true;
				return;
			end;
		else
			if math.random(1, 2) % 2 then
				u1.Velocity = u1.Velocity + Vector3.new(0, 0, 10 * (math.random(0, 1) * 2 - 1));
				return;
			end;
			u1.Velocity = u1.Velocity + Vector3.new(10 * (math.random(0, 1) * 2 - 1), 0, 0);
		end;
	end;
end);
local u10 = false;
l__Head__5.Touched:connect(function(p14)
	if p14 and p14.Parent and p14.Transparency < 1 and p14.CanCollide then
		local v61 = p14.Parent:findFirstChild("Humanoid") or p14.Parent.Parent:findFirstChild("Humanoid");
		if v61 then
			if v61.Health > 0 and not v61.Parent:findFirstChild("MainControlNPC") then
				u10 = true;
				return;
			end;
		elseif not u9 then

		end;
	end;
end);
local u11 = 0;
u1.TouchEnded:connect(function(p15)
	if p15 and p15.Parent and p15.Transparency < 1 and p15.CanCollide then
		local v62 = p15.Parent:findFirstChild("Humanoid") or p15.Parent.Parent:findFirstChild("Humanoid");
		if v62 and (game.Players:findFirstChild(v62.Parent.Name) and v62.Health > 0) and not v62.Parent:findFirstChild("MainControlNPC") then
			u9 = false;
			if not u10 then
				u11 = 0;
			end;
		end;
	end;
end);
l__Head__5.TouchEnded:connect(function(p16)
	if p16 and p16.Parent and p16.Transparency < 1 and p16.CanCollide then
		local v63 = p16.Parent:findFirstChild("Humanoid") or p16.Parent.Parent:findFirstChild("Humanoid");
		if v63 and (game.Players:findFirstChild(v63.Parent.Name) and v63.Health > 0) and not v63.Parent:findFirstChild("MainControlNPC") then
			u10 = false;
			if not u9 then
				u11 = 0;
			end;
		end;
	end;
end);
local l__UnderAttack__12 = l__Stats__6.UnderAttack;
local u13 = 0;
l__Humanoid__3.ChildAdded:connect(function()
	if l__Humanoid__3:findFirstChild("creator") and not l__UnderAttack__12.Value then
		l__UnderAttack__12.Value = true;
		u13 = 10;
	end;
end);
l__Humanoid__3.ChildRemoved:connect(function()
	if not l__Humanoid__3:findFirstChild("creator") and l__UnderAttack__12.Value then
		l__UnderAttack__12.Value = false;
	end;
end);
local v64 = Instance.new("Part");
v64.Name = "Home";
v64.Transparency = 1;
v64.CanCollide = false;
v64.Anchored = true;
v64.CFrame = CFrame.new(u1.Position);
v64.Parent = u2;
local u14 = "Standing";
local u15 = 0;
function followEnemy(p17)
	local l__magnitude__65 = (p17.Position - u1.Position).magnitude;
	if l__magnitude__65 < 10 then
		l__Humanoid__3.WalkSpeed = l__Stats__6.Speed.Value - (10 - l__magnitude__65) * (10 - l__magnitude__65) / (l__magnitude__65 * 100) * l__Stats__6.Speed.Value;
		if l__magnitude__65 < 5 then
			if u14 == "Pacing" then

			else
				return;
			end;
		else
			return;
		end;
	else
		l__Humanoid__3.WalkSpeed = l__Stats__6.Speed.Value;
		return;
	end;
	u15 = 0;
end;
local u16 = l__Value__8 / 2;
function DirectionRayIgnoreCheck(p18, p19)
	if p18 then
		if p18.Name == "Glass" then

		elseif p18.Name == "Averter" then
			return true;
		else
			return false;
		end;
	else
		return false;
	end;
	if (p18.Position - u1.Position).magnitude < u16 * 1.5 then
		if checkSight(p19) then
			onFireNormal(l__Head__5, p18);
		end;
	end;
	return true;
end;
function DirectionRayCast(p20, p21, p22)
	local v66, v67 = workspace:FindPartOnRay(Ray.new(p20, p21 * p22), u2);
	if v66 then
		if v67 then
			local v68 = p22 - (v67 - p20).magnitude;
			if DirectionRayIgnoreCheck(v66, v67) then
				if 0 < v68 then
					--return DirectionRayCast(v67, p21, v68);
				end;
			end;
		end;
	end;
	return v66, v67;
end;
function checkSight(p23)
	local v69 = Instance.new("Part");
	v69.Name = "Sight1";
	v69.Size = Vector3.new(1, 1, 1);
	v69.CanCollide = false;
	v69.Transparency = 1;
	local v70 = Instance.new("Weld");
	v70.Parent = u1;
	v70.Part0 = u1;
	v70.Part1 = v69;
	v70.C1 = v70.C1 + Vector3.new(16, 0, 12);
	v69.Parent = u2;
	local v71 = Instance.new("Part");
	v71.Name = "Sight2";
	v71.Size = Vector3.new(1, 1, 1);
	v71.CanCollide = false;
	v71.Transparency = 1;
	local v72 = Instance.new("Weld");
	v72.Parent = u1;
	v72.Part0 = u1;
	v72.Part1 = v71;
	v72.C1 = v72.C1 + Vector3.new(-16, 0, 12);
	v71.Parent = u2;
	local v73 = v69.Position - u1.Position;
	local v74 = v71.Position - u1.Position;
	local v75 = math.acos((v73.X * v74.X + v73.Y * v74.Y + v73.Z * v74.Z) / (v73.magnitude * v74.magnitude + 0.001));
	local v76 = Vector3.new(p23.X, 0, p23.Z) - u1.Position;
	local v77 = v69.Position - u1.Position;
	local v78 = math.acos((v76.X * v77.X + v76.Y * v77.Y + v76.Z * v77.Z) / (v76.magnitude * v77.magnitude + 0.001));
	local v79 = Vector3.new(p23.X, 0, p23.Z) - u1.Position;
	local v80 = v71.Position - u1.Position;
	local v81 = math.acos((v79.X * v80.X + v79.Y * v80.Y + v79.Z * v80.Z) / (v79.magnitude * v80.magnitude + 0.001));
	v69:Destroy();
	v70:Destroy();
	v71:Destroy();
	v72:Destroy();
	if v78 < v75 then
		if v81 < v75 then
			return true;
		end;
	end;
	return false;
end;
local u17 = nil;
local u18 = 0;
local l__Value__19 = l__Stats__6.Agressive.Value;
function findNearestTorso(p24)
	local v82 = l__CurrentCamera__4:getChildren();
	if l__CurrentCamera__4:findFirstChild("Level") then
		if l__CurrentCamera__4.Level:findFirstChild("NPC") then
			local v83 = l__CurrentCamera__4.Level.NPC:getChildren();
			for _, thing in v83 do
				if thing:IsA("Model") and thing:FindFirstChild("Humanoid") then
					if thing:FindFirstChild("MainControlVRT") then
						table.insert(v82, thing)
					end
				end
			end
		end
	end;
	local v86 = #v82;
	local v87 = 1 - 1;
	while true do
		if v82[v87] then
			if v82[v87]:IsA("Model") then
				if v82[v87] ~= u2 then
					if not l__Value__19 then
						if l__UnderAttack__12.Value then
							local v88 = v82[v87]:findFirstChild("Torso");
							local v89 = v82[v87]:findFirstChild("Humanoid");
							if v88 then
								if v89 then
									if not v82[v87]:findFirstChild("MainControlNPC") then
										if (v88.Position - p24).magnitude <= l__Value__8 then
											if 0 < v89.Health then
												if math.abs(v88.Position.Y - p24.Y) < 16 then
													local v90, v91 = DirectionRayCast(p24, (v88.Position - p24).unit, l__Value__8);
													local v92 = false;
													if v90 then
														if v90:IsDescendantOf(v82[v87]) then
															v92 = true;
														end;
													end;
													if not v92 then
														if l__UnderAttack__12.Value then
															if u17 then
																if v92 then
																	if (v88.Position - p24).magnitude < (u17.Position - p24).magnitude then
																		u18 = 10;
																		u17 = v88;
																	elseif v88 == u17 then
																		u18 = 10;
																	end;
																elseif not l__UnderAttack__12.Value then
																	if (v88.Position - p24).magnitude < 4 then
																		u18 = 10;
																		u17 = v88;
																	elseif checkSight(v91) then
																		u18 = 10;
																		u17 = v88;
																	end;
																else
																	u18 = 10;
																	u17 = v88;
																end;
															elseif not l__UnderAttack__12.Value then
																if (v88.Position - p24).magnitude < 4 then
																	u18 = 10;
																	u17 = v88;
																elseif checkSight(v91) then
																	u18 = 10;
																	u17 = v88;
																end;
															else
																u18 = 10;
																u17 = v88;
															end;
														elseif v88 == u17 then
															if u17 then
																u18 = u18 - 1;
																if u18 < -40 then
																	u17 = nil;
																	l__UnderAttack__12.Value = false;
																elseif u18 ~= 0 then
																	if u18 ~= -10 then
																		if u18 ~= -20 then
																			if u18 == -30 then
																				calculatePacing();
																			end;
																		else
																			calculatePacing();
																		end;
																	else
																		calculatePacing();
																	end;
																else
																	calculatePacing();
																end;
															end;
														end;
													elseif u17 then
														if v92 then
															if (v88.Position - p24).magnitude < (u17.Position - p24).magnitude then
																u18 = 10;
																u17 = v88;
															elseif v88 == u17 then
																u18 = 10;
															end;
														elseif not l__UnderAttack__12.Value then
															if (v88.Position - p24).magnitude < 4 then
																u18 = 10;
																u17 = v88;
															elseif checkSight(v91) then
																u18 = 10;
																u17 = v88;
															end;
														else
															u18 = 10;
															u17 = v88;
														end;
													elseif not l__UnderAttack__12.Value then
														if (v88.Position - p24).magnitude < 4 then
															u18 = 10;
															u17 = v88;
														elseif checkSight(v91) then
															u18 = 10;
															u17 = v88;
														end;
													else
														u18 = 10;
														u17 = v88;
													end;
												end;
											end;
										end;
									end;
								end;
							end;
						end;
					else
						local v88 = v82[v87]:findFirstChild("Torso");
						local v89 = v82[v87]:findFirstChild("Humanoid");
						if v88 then
							if v89 then
								if not v82[v87]:findFirstChild("MainControlNPC") then
									if (v88.Position - p24).magnitude <= l__Value__8 then
										if 0 < v89.Health then
											if math.abs(v88.Position.Y - p24.Y) < 16 then
												v90, v91 = DirectionRayCast(p24, (v88.Position - p24).unit, l__Value__8);
												v92 = false;
												if v90 then
													if v90:IsDescendantOf(v82[v87]) then
														v92 = true;
													end;
												end;
												if not v92 then
													if l__UnderAttack__12.Value then
														if u17 then
															if v92 then
																if (v88.Position - p24).magnitude < (u17.Position - p24).magnitude then
																	u18 = 10;
																	u17 = v88;
																elseif v88 == u17 then
																	u18 = 10;
																end;
															elseif not l__UnderAttack__12.Value then
																if (v88.Position - p24).magnitude < 4 then
																	u18 = 10;
																	u17 = v88;
																elseif checkSight(v91) then
																	u18 = 10;
																	u17 = v88;
																end;
															else
																u18 = 10;
																u17 = v88;
															end;
														elseif not l__UnderAttack__12.Value then
															if (v88.Position - p24).magnitude < 4 then
																u18 = 10;
																u17 = v88;
															elseif checkSight(v91) then
																u18 = 10;
																u17 = v88;
															end;
														else
															u18 = 10;
															u17 = v88;
														end;
													elseif v88 == u17 then
														if u17 then
															u18 = u18 - 1;
															if u18 < -40 then
																u17 = nil;
																l__UnderAttack__12.Value = false;
															elseif u18 ~= 0 then
																if u18 ~= -10 then
																	if u18 ~= -20 then
																		if u18 == -30 then
																			calculatePacing();
																		end;
																	else
																		calculatePacing();
																	end;
																else
																	calculatePacing();
																end;
															else
																calculatePacing();
															end;
														end;
													end;
												elseif u17 then
													if v92 then
														if (v88.Position - p24).magnitude < (u17.Position - p24).magnitude then
															u18 = 10;
															u17 = v88;
														elseif v88 == u17 then
															u18 = 10;
														end;
													elseif not l__UnderAttack__12.Value then
														if (v88.Position - p24).magnitude < 4 then
															u18 = 10;
															u17 = v88;
														elseif checkSight(v91) then
															u18 = 10;
															u17 = v88;
														end;
													else
														u18 = 10;
														u17 = v88;
													end;
												elseif not l__UnderAttack__12.Value then
													if (v88.Position - p24).magnitude < 4 then
														u18 = 10;
														u17 = v88;
													elseif checkSight(v91) then
														u18 = 10;
														u17 = v88;
													end;
												else
													u18 = 10;
													u17 = v88;
												end;
											end;
										end;
									end;
								end;
							end;
						end;
					end;
				end;
			end;
		end;
		if 0 <= 1 then
			if v87 < v86 then

			else
				break;
			end;
		elseif v86 < v87 then

		else
			break;
		end;
		v87 = v87 + 1;	
	end;
end;
local u20 = nil;
function calculatePacing()
	if not u17 then
		if v11 then
			v64.CFrame = CFrame.new(l__Path__10[tostring(l__Path__10.Value)].Value);
			l__Path__10.Value = l__Path__10.Value + 1;
			if #v12 < l__Path__10.Value then
				l__Path__10.Value = 1;
			end;
		else
			v64.CFrame = CFrame.new(u1.Position) + Vector3.new(math.random(-30, 30), 0, math.random(-30, 30));
		end;
	else
		v64.CFrame = CFrame.new(u17.Position) + Vector3.new(12 * (math.random(0, 1) * 2 - 1), 0, 12 * (math.random(0, 1) * 2 - 1));
	end;
	u20 = v64;
	local v93, v94 = DirectionRayCast(u1.Position, (v64.Position - u1.Position).unit, l__Value__8);
	if (v94 - u1.Position).magnitude < (v64.CFrame.p - u1.Position).magnitude then
		v64.CFrame = CFrame.new(v94);
	end;
end;
function enemyLost()
	if not l__Stats__6.Mode.Value then
		l__Stats__6.Mode.Value = true;
	end;
	if u15 <= 0 then
		if v11 then
			if #v12 <= 1 then
				if u20 then
					if (u20.Position - u1.Position).magnitude < 3 then
						u14 = "Standing";
					else
						u14 = "Pacing";
					end;
				else
					u14 = "Pacing";
				end;
			else
				u14 = "Pacing";
			end;
		else
			u14 = "Pacing";
		end;
		u15 = 60;
		calculatePacing();
		return;
	end;
	if v11 then
		if #v12 <= 1 then
			if u20 then
				if (u20.Position - u1.Position).magnitude < 3 then
					u14 = "Standing";
				else
					u14 = "Pacing";
				end;
			else
				u14 = "Pacing";
			end;
		else
			u14 = "Pacing";
		end;
	else
		u14 = "Pacing";
	end;
	u15 = u15 - 1;
end;
l__Stats__6.EnemyFound.Changed:connect(function()
	if not l__Stats__6.EnemyFound.Value then
		u15 = 12;
		u14 = "Standing";
		u20 = nil;
		enemyLost();
	end;
end);
local u21 = l__Stats__6.OffsetMaxX.Value + l__Torso__4.Position.X;
local u22 = l__Stats__6.OffsetMaxZ.Value + l__Torso__4.Position.Z;
local u23 = l__Stats__6.OffsetMinX.Value + l__Torso__4.Position.X;
local u24 = l__Stats__6.OffsetMinZ.Value + l__Torso__4.Position.Z;
function move(p25)

end;
local function u25()
	u14 = "Following";
	if u18 >= 0 then
		u20 = u17;
	end;
	local l__magnitude__95 = (u17.Position - u1.Position).magnitude;
	
	if l__magnitude__95 < u16 and not u7 and checkSight(u17.Position) and u17.Parent:findFirstChild("Humanoid") and (u17.Parent.Humanoid.Health > 0 or u17.Parent.Humanoid.MaxHealth == 0) then

		if l__Stats__6.Mode.Value then
			coroutine.resume(coroutine.create(function()
				onFireNormal(l__Head__5, u17);
			end));
		end;
		
		if l__magnitude__95 < 10 then
			l__Stats__6.Mode.Value = false;
			return;
		else
			l__Stats__6.Mode.Value = true;
			return;
		end;
	end;
	if l__Value__8 < l__magnitude__95 and u13 == 0 then
		if u17 then
			u18 = u18 - 1;
			if u18 < -40 then
				u17 = nil;
				l__UnderAttack__12.Value = false;
				return;
			end;
			if u18 == 0 or u18 == -10 or u18 == -20 or u18 == -30 then
				calculatePacing();
				return;
			end;
		end;
	elseif u17.Parent.Humanoid.Health < 1 and u17.Parent.Humanoid.MaxHealth ~= 0 then
		u17 = nil;
	end;
end;
local function u26(p26)
	if u21 < u1.Position.X or u22 < u1.Position.Z or u1.Position.X < u23 or u1.Position.Z < u24 then
		if v11 then
			v64.CFrame = CFrame.new(l__Path__10[tostring(l__Path__10.Value)].Value);
			p26 = v64;
			u15 = 60;
			local v96, v97 = DirectionRayCast(u1.Position, (v64.Position - u1.Position).unit, l__Value__8);
			local v98 = v96;
		else
			v64.CFrame = CFrame.new((u21 + u23) / 2, u1.Position.Y, (u22 + u24) / 2);
			p26 = v64;
			u15 = 80;
			local v99, v100 = DirectionRayCast(u1.Position, (v64.Position - u1.Position).unit, l__Value__8);
			v98 = v99;
		end;
		if v98 and not v11 then
			wait();
			if math.random(1, 2) % 2 then
				local v101 = (u22 + u24) / 2;
				v64.CFrame = CFrame.new(u1.Position.X, u1.Position.Y, math.random(v101 - 4, v101 + 4));
				p26 = v64;
				local v102, v103 = DirectionRayCast(u1.Position, (v64.Position - u1.Position).unit, l__Value__8);
				local v104 = v102;
			else
				local v105 = (u21 + u23) / 2;
				v64.CFrame = CFrame.new(math.random(v105 - 4, v105 + 4), u1.Position.Y, u1.Position.Z);
				p26 = v64;
				local v106, v107 = DirectionRayCast(u1.Position, (v64.Position - u1.Position).unit, l__Value__8);
				v104 = v106;
			end;
			if v104 then
				v64.CFrame = CFrame.new((u21 + u23) / 2, u1.Position.Y, (u22 + u24) / 2);
				p26 = v64;
			end;
		end;
	end;
	l__Humanoid__3:MoveTo(p26.Position, p26);
end;
function runBot(p27)
	local v108 = nil;
	move(p27);
	if 0 < l__Humanoid__3.Health then

	else
		u14 = "Standing";
		u20 = nil;
		return;
	end;
	u13 = u13 + 1;
	if 9 < u13 then
		u13 = 0;
		findNearestTorso(u1.Position);
	end;
	if u17 then
		l__Stats__6.State.Value = 2;
		l__Stats__6.EnemyFound.Value = true;
		u25();
	else
		if l__Value__19 then
			l__Stats__6.State.Value = 1;
		else
			l__Stats__6.State.Value = 0;
		end;
		if l__Stats__6.EnemyFound.Value then
			l__Stats__6.EnemyFound.Value = false;
		else
			enemyLost();
		end;
	end;
	if u20 then
		u26(u20);
		followEnemy(u20);
	else
		u26(u1);
	end;
	if not u9 then
		if u10 then
			print(u11);
			u11 = u11 + 1;
		end;
	else
		print(u11);
		u11 = u11 + 1;
	end;
	if 10 < u11 then
		l__UnderAttack__12.Value = true;
	end;
	local v109, v110, v111 = u1.CFrame:toEulerAnglesXYZ();
	v108 = math.deg(v110 + math.pi / 2);
	
	local v112
	
	if 0 < u1.CFrame.lookVector.Z then
		v112 = v108 + 180;
	else
		v112 = 180 - v108;
	end;
	
	l__Stats__6.RadarRotation.Value = math.ceil(v112 + 180);
end;
if l__Stats__6.WaitTime.Value > 0 then
	wait(l__Stats__6.WaitTime.Value);
end;
while u2 and u2.Parent do
	local v113, v114 = wait();
	if not u2 then
		break;
	end;
	if not u2.Parent then
		break;
	end;
	if script.Parent:findFirstChild("LocalScript") and script.Parent.LocalScript:findFirstChild("LocalPause") then
		if not script.Parent.LocalScript.LocalPause.Value or l__CurrentCamera__4.CameraType == "Scriptable" then
			if l__Humanoid__3.WalkSpeed == 0 then
				l__Humanoid__3.WalkSpeed = l__Stats__6.Speed.Value;
			end;
			runBot(v114);
			for v115 = 1, 3 do
				wait();
				if not u2 then
					break;
				end;
				if not u2.Parent then
					break;
				end;
			end;
		elseif l__Humanoid__3.WalkSpeed ~= 0 then
			l__Humanoid__3.WalkSpeed = 0;
		end;
	else
		runBot(v114);
	end;
end;
script:Destroy();
