-- Decompiled with the Synapse X Luau decompiler.

print("Running Repressilator Script");

local l__Value__1 = script.LinkedModel.Value;
local l__Debris__2 = game:GetService("Debris");
local l__Humanoid__3 = l__Value__1.Humanoid;

game:GetService("ScriptContext").Error:Connect(function(Error, trace, erroredScript)
	if erroredScript == script then
		warn("Error generated by: " .. l__Humanoid__3.Parent.Name)
		warn(Error)
	end
end)


local l__Torso__4 = l__Value__1.Torso;
local l__Stats__5 = l__Value__1.Stats;
local v6 = { l__Value__1:findFirstChild("Left Leg"), l__Value__1:findFirstChild("Right Leg") };
local v7 = { l__Value__1:findFirstChild("Left Arm"), l__Value__1:findFirstChild("Right Arm") };
local v8 = CFrame.new(1.2, 0.3, 0.55) * CFrame.Angles(-1.9198621771937625, 0.4363323129985824, 0);
local v9 = CFrame.new(-1.2, 0.3, 0.56) * CFrame.Angles(-1.9198621771937625, -0.4363323129985824, 0);
playerStats = game.Players.LocalPlayer.Stats
l__Humanoid__3.MaxHealth = l__Stats__5.Health.Value * (playerStats.Difficulty.Value / 3);
l__Humanoid__3.Health = l__Humanoid__3.MaxHealth;
l__Humanoid__3.WalkSpeed = l__Stats__5.Speed.Value;
local l__Value__10 = l__Stats__5.Authority.Value;
local l__Value__11 = l__Stats__5.Range.Value;
local v12 = math.random(0, 1);
local l__Path__13 = l__Stats__5.Path;
local v14 = false;
local v15 = l__Path__13:GetChildren();
if #v15 > 0 then
	v14 = true;
end;
local v16 = {
	None = {
		damage = 0, 
		range = 0, 
		type = "Normal", 
		weldLA = CFrame.new(1.5, 0, 0) * CFrame.Angles(0, 0, 0), 
		weldRA = CFrame.new(-1.5, 0, 0) * CFrame.Angles(0, 0, 0)
	}, 
	Pistol = {
		reticle = "NormalGun", 
		spread = 0.075, 
		ammo = 16, 
		damage = 10, 
		range = 60, 
		recoil = 0.02, 
		type = "Ranged", 
		waitTime = 10, 
		weldLA = CFrame.new(1, 0.4, 0.45) * CFrame.Angles(-1.5707963267948966, 1.0471975511965976, 0), 
		weldRA = CFrame.new(-1.2, 0.2, 0.46) * CFrame.Angles(-1.5707963267948966, -0.2617993877991494, 0), 
		weldTool = CFrame.new(0.3, -0.2, 1.3) * CFrame.Angles(1.5707963267948966, 0, -0.2617993877991494)
	}, 
	["Machine Pistol"] = {
		reticle = "NormalGun", 
		spread = 0.15, 
		ammo = 30, 
		damage = 6, 
		range = 50, 
		recoil = 0.02, 
		type = "Ranged", 
		waitTime = 4, 
		weldLA = CFrame.new(1, 0.4, 0.45) * CFrame.Angles(-1.5707963267948966, 1.0471975511965976, 0), 
		weldRA = CFrame.new(-1.2, 0.2, 0.46) * CFrame.Angles(-1.5707963267948966, -0.2617993877991494, 0), 
		weldTool = CFrame.new(0.3, -1.2, 0) * CFrame.Angles(3.141592653589793, 0, -0.2617993877991494)
	}, 
	["Assault Rifle 1"] = {
		reticle = "NormalGun", 
		spread = 0.1, 
		ammo = 40, 
		damage = 6, 
		range = 70, 
		recoil = 0.02, 
		type = "Ranged", 
		waitTime = 6, 
		weldLA = CFrame.new(-0.39, 1.02, 0.8) * CFrame.Angles(-0.93, 0.13, -1.71), 
		weldRA = CFrame.new(-1.06, -0.38, 0.53) * CFrame.Angles(-1.33, -0.46, 0.14), 
		weldTool = CFrame.new(-0.15, 1.64, 0.39) * CFrame.Angles(-1.83, -1.36, -2.22)
	}, 
	Revolver = {
		reticle = "NormalGun", 
		spread = 0.05, 
		ammo = 8, 
		damage = 20, 
		range = 80, 
		recoil = 0.04, 
		type = "Ranged", 
		waitTime = 10, 
		weldLA = CFrame.new(0.63, 0.4, -0.54) * CFrame.Angles(-2.57, -0.07, 1.42), 
		weldRA = CFrame.new(-1.2, 0.2, 0.46) * CFrame.Angles(-1.5707963267948966, -0.2617993877991494, 0), 
		weldTool = CFrame.new(0.3, -1.5, -0.2) * CFrame.Angles(3.141592653589793, 0, -0.2617993877991494)
	}
};
function unanchor(p1)
	local v17 = p1:GetChildren();
	local v18 = #v17;
	local v19 = 1 - 1;
	while true do
		if v17[v19] then
			if v17[v19]:IsA("Part") then
				v17[v19].Anchored = false;
			elseif v17[v19] then
				if v17[v19]:IsA("Model") then
					unanchor(v17[v19]);
				end;
			end;
		elseif v17[v19] then
			if v17[v19]:IsA("Model") then
				unanchor(v17[v19]);
			end;
		end;
		if 0 <= 1 then
			if v19 < v18 then

			else
				break;
			end;
		elseif v18 < v19 then

		else
			break;
		end;
		v19 = v19 + 1;	
	end;
end;
unanchor(l__Value__1);
local v20 = Instance.new("BodyGyro");
v20.maxTorque = Vector3.new(4000000000000, 0, 4000000000000);
v20.P = 10000;
v20.D = 400;
v20.Parent = l__Torso__4;

function waitTime(p5)
	for i = 0, p5 do
		task.wait(0.03)
		if script.Parent.GamePause.Value then
			script.Parent.GamePause.Changed:Wait()
		end
	end
end;

local v22 = Instance.new("Weld");
v22.Part0 = l__Torso__4;
v22.Parent = l__Torso__4;
v22.Part1 = v7[1];
v22.C1 = v8;
local v23 = Instance.new("Weld");
v23.Part0 = l__Torso__4;
v23.Parent = l__Torso__4;
v23.Part1 = v7[2];
v23.C1 = v9;
l__Torso__4["Left Shoulder"].Part1 = nil;
l__Torso__4["Right Shoulder"].Part1 = nil;
local l__CurrentCamera__1 = workspace.CurrentCamera;
local l__GameItems__2 = game.ReplicatedStorage.GameItems;
function visualDamage(p3, p4, p5)
	local v24 = Instance.new("BillboardGui");
	v24.Size = UDim2.new(1, 0, 1, 0);
	v24.StudsOffset = Vector3.new(math.random(-1, 1), 1.65, math.random(-1, 1));
	local v25 = l__GameItems__2.MasterGuis.DamageFrame:clone();
	v25.Parent = v24;
	if p4 == 0 then
		v25.TextLabel.Text = "-" .. p4;
		v25.TextLabel.TextStrokeColor3 = Color3.new(0, 0, 1);
	elseif p4 < 0 then
		v25.TextLabel.Text = "+" .. p4;
		v25.TextLabel.TextStrokeColor3 = Color3.new(0, 1, 0);
	else
		v25.TextLabel.Text = "-" .. p4;
		v25.TextLabel.TextStrokeColor3 = Color3.new(1, 0, 0);
	end;
	v24.Parent = p5;
	v24.Adornee = p5;
	local l__BillboardControl__26 = v25.BillboardControl;
	l__BillboardControl__26.Billboard.Value = v24;
	l__BillboardControl__26.Parent = script.Parent;
	l__BillboardControl__26.Disabled = false;
	l__Debris__2:AddItem(v24, 5);
end;
local function u3(p6)
	local l__X__27 = p6.Position.X;
	local l__Y__28 = p6.Position.Y;
	local l__Z__29 = p6.Position.Z;
	local l__X__30 = p6.Size.X;
	local l__Y__31 = p6.Size.Y;
	local l__Z__32 = p6.Size.Z;
	local v33 = p6.CFrame - p6.CFrame.p;
	p6:Destroy();
	local v34 = Instance.new("Part");
	v34.Name = "Averter";
	v34.FormFactor = 0;
	v34.Size = Vector3.new(1, 1, 1);
	v34.BrickColor = p6.BrickColor;
	v34.Shape = 1;
	v34.BottomSurface = 0;
	v34.TopSurface = 0;
	v34.Reflectance = p6.Reflectance;
	v34.Transparency = p6.Transparency;
	v34.CanCollide = false;
	for v35 = 0, l__X__30 - 1 do
		for v36 = 0, l__Y__31 - 1 do
			for v37 = 0, l__Z__32 - 1 do
				local v38 = v34:clone();
				v38.Velocity = Vector3.new(math.random(-20, 20), math.random(-20, 20), math.random(-20, 20));
				v38.CFrame = CFrame.new(l__X__27 - (l__X__30 - 1) / 2 + v35, l__Y__28 - (l__Y__31 - 1) / 2 + v36, l__Z__29 - (l__Z__32 - 1) / 2 + v37) * v33;
				l__Debris__2:AddItem(v38, 0.5);
				v38.Parent = l__CurrentCamera__1;
			end;
		end;
	end;
end;
function normalDamage(p7, p8)
	local v39 = p7.Parent:findFirstChild("Humanoid") or p7.Parent.Parent:findFirstChild("Humanoid");
	if v39 then
		if not game.Players:findFirstChild(v39.Parent.Name) then
			if v39.Parent:findFirstChild("MainControlVRT") then
				if 0 < v39.Health then
					if not v39.Parent:findFirstChild("ForceField") then
						if v39.Parent:findFirstChild("Head") then
							local v40 = math.ceil(p8 * playerStats.Difficulty.Value / 3);
							if p7.Name == "Head" then
								v40 = math.ceil(v40 * 2);
							elseif p7.Name == "Torso" then
								v40 = math.ceil(v40 * 1.5);
							end;
							v39:TakeDamage(v40);
							visualDamage(v39, v40, v39.Parent.Head);
							return;
						end;
					end;
				end;
			else
				if p7.Name == "Glass" then
					u3(p7);
					return;
				end;
				if p7.Name == "Explosive" then
					if p7:findFirstChild("Explode") then
						p7.Explode.Value = true;
					end;
				end;
			end;
		elseif 0 < v39.Health then
			if not v39.Parent:findFirstChild("ForceField") then
				if v39.Parent:findFirstChild("Head") then
					local v40 = math.ceil(p8 * playerStats.Difficulty.Value / 3);
					if p7.Name == "Head" then
						v40 = math.ceil(v40 * 2);
					elseif p7.Name == "Torso" then
						v40 = math.ceil(v40 * 1.5);
					end;
					v39:TakeDamage(v40);
					visualDamage(v39, v40, v39.Parent.Head);
					return;
				end;
			end;
		end;
	else
		if p7.Name == "Glass" then
			u3(p7);
			return;
		end;
		if p7.Name == "Explosive" then
			if p7:findFirstChild("Explode") then
				p7.Explode.Value = true;
			end;
		end;
	end;
end;
local u4 = false;
local u5 = v8;
local u6 = v9;
function laserBall(p9, p10)
	u4 = true;
	step = 15;
	local v41 = 1 - 1;
	while true do
		u5 = CFrame.new(1.5 - 0.03 * v41, 0 + 0.05 * v41, 0 + 0.05 * v41) * CFrame.Angles(math.rad(-8 - 7 * v41), 0, (math.rad(-1 * v41)));
		u6 = CFrame.new(-1.5 + 0.03 * v41, 0 + 0.05 * v41, 0 + 0.05 * v41) * CFrame.Angles(math.rad(-8 - 7 * v41), 0, (math.rad(1 * v41)));
		waitTime(1);
		if 0 <= 1 then
			if v41 < step then

			else
				break;
			end;
		elseif step < v41 then

		else
			break;
		end;
		v41 = v41 + 1;	
	end;
	local v42 = Instance.new("Part");
	v42.Shape = "Block";
	v42.formFactor = "Symmetric";
	v42.Size = Vector3.new(1, 1, 1);
	v42.BrickColor = BrickColor.new("Bright red");
	v42.Transparency = 0.2;
	v42.TopSurface = 0;
	v42.BottomSurface = 0;
	v42.Locked = true;
	v42.Name = "Averter";
	v42.CFrame = CFrame.new(p9.CFrame * Vector3.new(0, 1, -3), p10.Position);
	v42.Parent = l__Value__1;
	local v43 = Instance.new("Weld");
	v43.Parent = p9;
	v43.Part0 = v43.Parent;
	v43.Part1 = v42;
	v43.C1 = CFrame.new(0, 0, 3);
	if script.Parent:FindFirstChild("SoundScript") then
		local v44 = Instance.new("StringValue");
		v44.Name = "Sound";
		v44.Value = "LaserCharge";
		local v45 = Instance.new("ObjectValue");
		v45.Name = "Location";
		v45.Value = l__Torso__4;
		v45.Parent = v44;
		v44.Parent = script.Parent.SoundScript.Effects;
	end;
	local v46 = Instance.new("SpecialMesh");
	v46.MeshType = "Sphere";
	v46.Scale = Vector3.new(0.1, 0.1, 0.1);
	v46.Parent = v42;
	local v47 = 1 - 1;
	while true do
		waitTime(2);
		u5 = CFrame.new(1.05, 0.75, 0.75) * CFrame.Angles(-1.9722220547535925, math.rad(0 + -4 * v47), (math.rad(-15 + -2 * v47)));
		u6 = CFrame.new(-1.05, 0.75, 0.75) * CFrame.Angles(-1.9722220547535925, math.rad(0 + 4 * v47), (math.rad(15 - -2 * v47)));
		v46.Scale = Vector3.new(0.2 * v47, 0.2 * v47, 0.2 * v47);
		if l__Humanoid__3.Health < 1 then
			v42:Destroy();
			return;
		end;
		if 0 <= 1 then
			if v47 < 20 then

			else
				break;
			end;
		elseif 20 < v47 then

		else
			break;
		end;
		v47 = v47 + 1;	
	end;
	local v48 = Instance.new("Part");
	v48.Shape = "Block";
	v48.formFactor = "Symmetric";
	v48.Size = Vector3.new(2, 2, 2);
	v48.BrickColor = BrickColor.new("Bright red");
	v48.Transparency = 0.2;
	v48.TopSurface = 0;
	v48.BottomSurface = 0;
	v48.CanCollide = false;
	v48.Locked = true;
	v48.Name = "Averter";
	v48.CFrame = CFrame.new(p9.CFrame * Vector3.new(0, 1, -5), p10.Position);
	local v49 = Instance.new("SpecialMesh");
	v49.MeshType = "Sphere";
	v49.Scale = Vector3.new(1, 1, 1);
	v49.Parent = v48;
	local v50 = Instance.new("BodyVelocity");
	v50.velocity = p9.CFrame.lookVector * 50;
	v50.Parent = v48;
	local v51 = Instance.new("BodyAngularVelocity");
	v51.angularvelocity = Vector3.new(math.random(-1, 1), math.random(-1, 1), math.random(-1, 1));
	v51.Parent = v48;
	v43.Parent = nil;
	v42:Destroy();
	if script.Parent:FindFirstChild("SoundScript") then
		local v52 = Instance.new("StringValue");
		v52.Name = "Sound";
		v52.Value = "LaserBlast";
		local v53 = Instance.new("ObjectValue");
		v53.Name = "Location";
		v53.Value = l__Torso__4;
		v53.Parent = v52;
		v52.Parent = script.Parent.SoundScript.Effects;
	end;
	v48.Parent = l__CurrentCamera__1;
	v48.Touched:connect(function(p11)
		if p11 then
			if p11.Parent then
				normalDamage(p11, 20, l__Stats__5.Tool.Value);
				v48:Destroy();
			end;
		end;
	end);
	local v54 = 1 - 1;
	while true do
		u5 = CFrame.new(1.5 - 0.03 * (15 - v54), 0 + 0.05 * (15 - v54), 0 + 0.05 * (15 - v54)) * CFrame.Angles(math.rad(-8 - 7 * (15 - v54)), 0, (math.rad(-1 * (15 - v54))));
		u6 = CFrame.new(-1.5 + 0.03 * (15 - v54), 0 + 0.05 * (15 - v54), 0 + 0.05 * (15 - v54)) * CFrame.Angles(math.rad(-8 - 7 * (15 - v54)), 0, (math.rad(1 * (15 - v54))));
		waitTime(1);
		if 0 <= 1 then
			if v54 < step then

			else
				break;
			end;
		elseif step < v54 then

		else
			break;
		end;
		v54 = v54 + 1;	
	end;
	if p9:findFirstChild("LaserCharge") then
		p9.LaserCharge:Stop();
	end;
	waitTime(10);
	u4 = false;
end;
local v55 = Instance.new("Part");
v55.FormFactor = Enum.FormFactor.Custom;
v55.Size = Vector3.new(0.2, 0.2, 1);
v55.BrickColor = BrickColor.new("Bright red");
v55.CanCollide = false;
v55.Anchored = true;
v55.Transparency = 0.3;
v55.TopSurface = Enum.SurfaceType.Smooth;
v55.BottomSurface = Enum.SurfaceType.Smooth;
v55.Name = "Averter";
local u7 = 0.1;
local u8 = l__Value__11 / 2;
function onFireNormal(p12, p13)
	u4 = true;
	local function u9(p14, p15)
		if p14 then
			if not (1 <= p14.Transparency) then
				if string.lower(p14.Name) ~= "water" then
					if p14.Name ~= "Effect" then
						if p14.Name ~= "Rocket" then
							if p14.Name ~= "Averter" then
								if p14.Parent.ClassName ~= "Hat" then
									if p14.Parent.ClassName == "Tool" then

									else
										return false;
									end;
								end;
							end;
						end;
					end;
				end;
			end;
		else
			return false;
		end;
		return true;
	end;
	local function u10(p16, p17, p18)
		local v56, v57 = workspace:FindPartOnRay(Ray.new(p16 + p17 * 0.01, p17 * p18), l__Value__1);
		if v56 then
			if v57 then
				local v58 = p18 - (v57 - p16).magnitude;
				if u9(v56, v57) then
					if 0 < v58 then
						return u10(v57, p17, v58);
					end;
				end;
			end;
		end;
		return v56, v57;
	end;
	local v59 = (p13.Position - p12.Position).unit;
	if p13.Name ~= "Glass" then
		v59 = (CFrame.new(Vector3.new(0, 0, 0), v59) * CFrame.Angles(0, 0, math.random() * 2 * math.pi) * CFrame.Angles(math.random() * u7, 0, 0)).lookVector;
	end;
	local v60, v61 = u10(p12.Position, v59, u8);
	if script.Parent:FindFirstChild("SoundScript") then
		local v62 = Instance.new("StringValue");
		v62.Name = "Sound";
		v62.Value = "LaserShot";
		local v63 = Instance.new("ObjectValue");
		v63.Name = "Location";
		v63.Value = l__Torso__4;
		v63.Parent = v62;
		v62.Parent = script.Parent.SoundScript.Effects;
	end;
	if v61 then
		local v64 = v55:clone();
		local l__magnitude__65 = (v61 - p12.Position).magnitude;
		v64.CFrame = CFrame.new(v61, p12.Position) * CFrame.new(0, 0, -l__magnitude__65 / 2);
		local v66 = Instance.new("BlockMesh");
		v66.Scale = Vector3.new(1, 1, l__magnitude__65 - 2);
		v66.Offset = Vector3.new(0, 0, 2);
		v66.Parent = v64;
		v64.Parent = l__CurrentCamera__1;
		l__Debris__2:AddItem(v64, 0.06);
	end;
	if v60 then
		if v60.Parent then
			if v61 then
				normalDamage(v60, v16[l__Stats__5.Tool.Value].damage / 2);
			end;
		end;
	end;
	waitTime(v16[l__Stats__5.Tool.Value].waitTime);
	u4 = false;
end;
local v67 = Instance.new("Part");
v67.FormFactor = "Symmetric";
v67.Size = Vector3.new(1, 1, 1);
v67.Transparency = 1;
v67.Name = "Sensor";
v67.CanCollide = false;
local v68 = Instance.new("Weld");
v68.Name = "SensorWeld";
v68.Parent = l__Torso__4;
v68.Part0 = l__Torso__4;
v68.Part1 = v67;
v67.Parent = l__Value__1;
local u11 = false;
v67.Touched:connect(function(p19)
	if u11 and p19 and p19.Parent then
		if not l__Stats__5.Mode.Value then
			normalDamage(p19, 10, l__Stats__5.Tool.Value);
		else
			normalDamage(p19, v16[l__Stats__5.Tool.Value].damage, l__Stats__5.Tool.Value);
		end;
		u11 = false;
	end;
end);
local u12 = nil;
local u13 = v8;
local u14 = nil;
local u15 = nil;
local u16 = v9;
local u17 = nil;
local function u18(p20, p21, p22, p23)
	local v69, v70, v71 = p20:toEulerAnglesXYZ();
	local v72, v73, v74 = p21:toEulerAnglesXYZ();
	return CFrame.new(p20.X + (p21.X - p20.X) / p23 * p22, p20.Y + (p21.Y - p20.Y) / p23 * p22, p20.Z + (p21.Z - p20.Z) / p23 * p22) * CFrame.Angles(v69 + (v72 - v69) / p23 * p22, v70 + (v73 - v70) / p23 * p22, v71 + (v74 - v71) / p23 * p22);
end;
function fists(p24)
	u4 = true;
	if p24 == 1 then
		u12 = u13;
		u14 = CFrame.new(1.6, 1.2, 0.55) * CFrame.Angles(-1.9198621771937625, 0.6981317007977318, 0.2617993877991494);
		u15 = u16;
		u17 = CFrame.new(-1.2, -0.6, -1.56) * CFrame.Angles(-2.792526803190927, 0.2617993877991494, -1.6580627893946132);
		u11 = true;
		v68.Part0 = v7[1];
		v68.C1 = v68.C1 + Vector3.new(0, 1, 0);
		step = 6;
		local v75 = 1 - 1;
		while true do
			u5 = u18(u12, u14, v75, step);
			u6 = u18(u15, u17, v75, step);
			waitTime(1);
			if 0 <= 1 then
				if v75 < step then

				else
					break;
				end;
			elseif step < v75 then

			else
				break;
			end;
			v75 = v75 + 1;		
		end;
		waitTime(1);
		step = 8;
		local v76 = 1 - 1;
		while true do
			u5 = u18(u14, u12, v76, step);
			u6 = u18(u17, u15, v76, step);
			waitTime(1);
			if 0 <= 1 then
				if v76 < step then

				else
					break;
				end;
			elseif step < v76 then

			else
				break;
			end;
			v76 = v76 + 1;		
		end;
		v68.Part0 = l__Torso__4;
		v68.C1 = v68.C1 - Vector3.new(0, 1, 0);
		u11 = false;
	else
		u12 = u13;
		u14 = CFrame.new(1.2, -0.6, -1.56) * CFrame.Angles(-2.792526803190927, -0.2617993877991494, 1.6580627893946132);
		u15 = u16;
		u17 = CFrame.new(-1.6, 1.2, 0.55) * CFrame.Angles(-1.9198621771937625, -0.6981317007977318, -0.2617993877991494);
		u11 = true;
		v68.Part0 = v7[2];
		v68.C1 = v68.C1 + Vector3.new(0, 1, 0);
		step = 6;
		local v77 = 1 - 1;
		while true do
			u5 = u18(u12, u14, v77, step);
			u6 = u18(u15, u17, v77, step);
			waitTime(1);
			if 0 <= 1 then
				if v77 < step then

				else
					break;
				end;
			elseif step < v77 then

			else
				break;
			end;
			v77 = v77 + 1;		
		end;
		waitTime(1);
		step = 8;
		local v78 = 1 - 1;
		while true do
			u5 = u18(u14, u12, v78, step);
			u6 = u18(u17, u15, v78, step);
			waitTime(1);
			if 0 <= 1 then
				if v78 < step then

				else
					break;
				end;
			elseif step < v78 then

			else
				break;
			end;
			v78 = v78 + 1;		
		end;
		v68.Part0 = l__Torso__4;
		v68.C1 = v68.C1 - Vector3.new(0, 1, 0);
		u11 = false;
	end;
	waitTime(2);
	u4 = false;
end;
local u19 = true;
local u20 = 0;
local u21 = 0.005;
local u22 = 0.07;
function getTransition()
	if u19 then
		u20 = u20 + u21;
		if u22 < u20 then

		else
			return;
		end;
	else
		u20 = u20 - u21;
		if u20 < -u22 then
			u19 = not u19;
		end;
		return;
	end;
	u19 = not u19;
end;
local l__Head__23 = l__Value__1.Head;
local u24 = 0;
local l__Neck__25 = l__Torso__4.Neck;
local u26 = "Standing";
function updateAim()
	local v79 = l__Head__23.CFrame.lookVector + l__Head__23.Position;
	local l__Position__80 = l__Head__23.Position;
	local v81 = (l__Position__80.y - v79.y) / (l__Position__80 - v79).magnitude;
	if 0.16 < u24 - v81 then
		v81 = u24 - 0.16;
	elseif u24 - v81 < -0.16 then
		v81 = u24 + 0.16;
	end;
	u24 = v81;
	l__Neck__25.C0 = CFrame.new(0, 1, 0, -1, -0, -0, 0, 0, 1, 0, 1, 0) * CFrame.Angles(v81, 0, 0);
	if v7 then
		if u26 ~= "Standing" then
			u22 = 0.03;
			u21 = 0.005;
			if u26 == "Running" then
				u22 = u22 * 5;
				u21 = u21 * 4;
			elseif u26 ~= "Pacing" then
				if u26 == "Following" then
					u22 = u22 * 2;
					u21 = u21 * 2;
				end;
			else
				u22 = u22 * 2;
				u21 = u21 * 2;
			end;
			getTransition();
		else
			u22 = 0;
			u21 = 0;
			getTransition();
		end;
		v22.C1 = u5 * CFrame.new(u20, math.abs(v81 * 0.4), -1.4 * v81 - 0.2) * CFrame.Angles(v81 * 1.2, u20 / 5, u20 / 5);
		v23.C1 = u6 * CFrame.new(u20, math.abs(v81 * 0.4), -1.4 * v81 - 0.2) * CFrame.Angles(v81 * 1.2, u20 / 5, u20 / 5);
	end;
end;
local u27 = false;
local u28 = nil;
local u29 = nil;
local u30 = 0.3;
function getCurrentTool()
	u27 = false;
	u12 = u5;
	u14 = CFrame.new(1.29, 0, 0.34) * CFrame.Angles(-0.52, 0, -0.17);
	u15 = u6;
	u17 = CFrame.new(-1.29, 0, 0.34) * CFrame.Angles(-0.52, 0, 0.17);
	step = 6;
	local v82 = 1 - 1;
	while true do
		u5 = u18(u12, u14, v82, step);
		u6 = u18(u15, u17, v82, step);
		waitTime(1);
		if 0 <= 1 then
			if v82 < step then

			else
				break;
			end;
		elseif step < v82 then

		else
			break;
		end;
		v82 = v82 + 1;	
	end;
	if u28 then
		u28:Destroy();
	end;
	if u29 then
		u29:Destroy();
	end;
	if l__Stats__5.Mode.Value then
		if l__Stats__5.Tool.Value ~= "None" then
			l__Stats__5.Spread.Value = v16[l__Stats__5.Tool.Value].spread;
			u7 = l__Stats__5.Spread.Value;
			u30 = l__Stats__5.Spread.Value * (4 - l__Stats__5.Spread.Value * 10);
			l__Stats__5.Ammo.Value = v16[l__Stats__5.Tool.Value].ammo;
			u13 = v16[l__Stats__5.Tool.Value].weldLA;
			u16 = v16[l__Stats__5.Tool.Value].weldRA;
			u5 = u13;
			u6 = u16;
			u28 = l__GameItems__2.MasterTools[l__Stats__5.Tool.Value]:clone();
			u29 = Instance.new("Weld");
			u29.Part0 = v7[2];
			u29.Parent = v7[2];
			u29.Part1 = u28;
			u29.C1 = v16[l__Stats__5.Tool.Value].weldTool;
			u28.Parent = l__Value__1;
			u12 = u5;
			u15 = u6;
			local v83 = 1 - 1;
			while true do
				u5 = u18(u14, u12, v83, step);
				u6 = u18(u17, u15, v83, step);
				waitTime(1);
				if 0 <= 1 then
					if v83 < step then

					else
						break;
					end;
				elseif step < v83 then

				else
					break;
				end;
				v83 = v83 + 1;			
			end;
		else
			l__Stats__5.Spread.Value = 0;
			u7 = l__Stats__5.Spread.Value;
			u30 = l__Stats__5.Spread.Value * 4;
			u13 = v16[l__Stats__5.Tool.Value].weldLA;
			u16 = v16[l__Stats__5.Tool.Value].weldRA;
			u5 = u13;
			u6 = u16;
			u12 = u5;
			u15 = u6;
			local v84 = 1 - 1;
			while true do
				u5 = u18(u14, u12, v84, step);
				u6 = u18(u17, u15, v84, step);
				waitTime(1);
				if 0 <= 1 then
					if v84 < step then

					else
						break;
					end;
				elseif step < v84 then

				else
					break;
				end;
				v84 = v84 + 1;			
			end;
		end;
	else
		l__Stats__5.Spread.Value = 0;
		u7 = l__Stats__5.Spread.Value;
		u30 = l__Stats__5.Spread.Value * 4;
		u13 = v8;
		u16 = v9;
		u5 = u13;
		u6 = u16;
		u12 = u5;
		u15 = u6;
		local v85 = 1 - 1;
		while true do
			u5 = u18(u14, u12, v85, step);
			u6 = u18(u17, u15, v85, step);
			waitTime(1);
			if 0 <= 1 then
				if v85 < step then

				else
					break;
				end;
			elseif step < v85 then

			else
				break;
			end;
			v85 = v85 + 1;		
		end;
	end;
	u27 = true;
end;
local u31 = false;
function runGettingTool()
	if u31 then
		return;
	end;
	print("Get tool");
	u31 = true;
	getCurrentTool();
	waitTime(1);
	u31 = false;
end;
l__Stats__5.Tool.Changed:connect(function()
	if l__Stats__5.Mode.Value then
		runGettingTool();
		return;
	end;
	l__Stats__5.Mode.Value = true;
end);
l__Stats__5.Mode.Changed:connect(function()
	runGettingTool();
end);
runGettingTool();
l__Humanoid__3.Died:connect(function()
	coroutine.resume(coroutine.create(function()
		waitTime(400);
		l__Value__1:Destroy();
		script:Destroy()
	end));
	waitTime(1);
	if l__Value__1:findFirstChild("Torso") and l__Torso__4.Position.y > -20 then
		local v86 = Instance.new("Explosion");
		v86.Position = l__Torso__4.Position;
		v86.BlastPressure = 0;
		v86.BlastRadius = 5;
		v86.Parent = l__CurrentCamera__1;
		l__Debris__2:AddItem(v86, 3);
		l__Value__1:BreakJoints();
		local v87 = script.Parent:FindFirstChild("SoundScript");
		if v87 then
			v87 = Instance.new("StringValue");
			v87.Name = "Sound";
			v87.Value = "RoboticExplosion";
			local v88 = Instance.new("ObjectValue");
			v88.Name = "Location";
			v88.Value = l__Torso__4;
			v88.Parent = v87;
			v87.Parent = script.Parent.SoundScript.Effects;
		end;
		local function u32(p25)
			local v89 = p25:GetChildren();
			for v90 = 1, #v89 do
				if v89[v90] and v89[v90]:IsA("Part") then
					v89[v90].Velocity = Vector3.new(math.random(-20, 20), math.random(-20, 20), math.random(-20, 20));
				elseif v89[v90] and v89[v90]:IsA("Model") then
					u32(v89[v90]);
				end;
			end;
		end;
		u32(l__Value__1);
		if l__CurrentCamera__1:findFirstChild("Level") and l__CurrentCamera__1.Level:findFirstChild("Tool") and l__GameItems__2.MasterTools:findFirstChild(l__Stats__5.Tool.Value) then
			local v91 = l__GameItems__2.MasterTools[l__Stats__5.Tool.Value]:clone();
			v91.CanCollide = true;
			v91.CFrame = l__Torso__4.CFrame;
			coroutine.resume(coroutine.create(function()
				while true do
					wait(0.09);
					if v91.Velocity.magnitude < 0.1 then
						break;
					end;				
				end;
				v91.Anchored = true;
			end));
			v91.Parent = l__CurrentCamera__1.Level.Tool;
			v91.Velocity = Vector3.new(math.random(-20, 20), math.random(-20, 20), math.random(-20, 20));
		end;
		if l__Stats__5.Counter.Value then
			l__Stats__5.Counter.Value.Value = l__Stats__5.Counter.Value.Value - 1;
		end;
		--script.LinkedModel.Value = nil;
		--waitTime(500);
		--script:Destroy();
	end;
end);
local u33 = false;
l__Torso__4.Touched:connect(function(p26)
	if p26 and p26.Parent and p26.Transparency < 1 and p26.CanCollide then
		local v92 = p26.Parent:findFirstChild("Humanoid") or p26.Parent.Parent:findFirstChild("Humanoid");
		if v92 then
			if v92.Health > 0 and not v92.Parent:findFirstChild("MainControlNPC") then
				u33 = true;
				return;
			end;
		else
			l__Humanoid__3.Jump = true;
			if math.random(1, 2) % 2 then
				l__Torso__4.Velocity = l__Torso__4.Velocity + Vector3.new(0, 0, 10 * (math.random(0, 1) * 2 - 1));
				return;
			end;
			l__Torso__4.Velocity = l__Torso__4.Velocity + Vector3.new(10 * (math.random(0, 1) * 2 - 1), 0, 0);
		end;
	end;
end);
local u34 = false;
l__Head__23.Touched:connect(function(p27)
	if p27 and p27.Parent and p27.Transparency < 1 and p27.CanCollide then
		local v93 = p27.Parent:findFirstChild("Humanoid") or p27.Parent.Parent:findFirstChild("Humanoid");
		if v93 then
			if v93.Health > 0 and not v93.Parent:findFirstChild("MainControlNPC") then
				u34 = true;
				return;
			end;
		elseif not u33 then

		end;
	end;
end);
local u35 = 0;
l__Torso__4.TouchEnded:connect(function(p28)
	if p28 and p28.Parent and p28.Transparency < 1 and p28.CanCollide then
		local v94 = p28.Parent:findFirstChild("Humanoid") or p28.Parent.Parent:findFirstChild("Humanoid");
		if v94 and (game.Players:findFirstChild(v94.Parent.Name) and v94.Health > 0) and not v94.Parent:findFirstChild("MainControlNPC") then
			u33 = false;
			if not u34 then
				u35 = 0;
			end;
		end;
	end;
end);
l__Head__23.TouchEnded:connect(function(p29)
	if p29 and p29.Parent and p29.Transparency < 1 and p29.CanCollide then
		local v95 = p29.Parent:findFirstChild("Humanoid") or p29.Parent.Parent:findFirstChild("Humanoid");
		if v95 and (game.Players:findFirstChild(v95.Parent.Name) and v95.Health > 0) and not v95.Parent:findFirstChild("MainControlNPC") then
			u34 = false;
			if not u33 then
				u35 = 0;
			end;
		end;
	end;
end);
local l__UnderAttack__36 = l__Stats__5.UnderAttack;
local u37 = 0;
l__Humanoid__3.ChildAdded:connect(function()
	if l__Humanoid__3:findFirstChild("creator") and not l__UnderAttack__36.Value then
		l__UnderAttack__36.Value = true;
		u37 = 10;
	end;
end);
l__Humanoid__3.ChildRemoved:connect(function()
	if not l__Humanoid__3:findFirstChild("creator") and l__UnderAttack__36.Value then
		l__UnderAttack__36.Value = false;
	end;
end);
local v96 = Instance.new("Part");
v96.Name = "Home";
v96.Transparency = 1;
v96.CanCollide = false;
v96.Anchored = true;
v96.CFrame = CFrame.new(l__Torso__4.Position);
v96.Parent = l__Value__1;
local u38 = 0;
function followEnemy(p30)
	local l__magnitude__97 = (p30.Position - l__Torso__4.Position).magnitude;
	if l__magnitude__97 < 10 then
		l__Humanoid__3.WalkSpeed = l__Stats__5.Speed.Value - (10 - l__magnitude__97) * (10 - l__magnitude__97) / (l__magnitude__97 * 100) * l__Stats__5.Speed.Value;
		if l__magnitude__97 < 5 then
			if u26 == "Pacing" then

			else
				return;
			end;
		else
			return;
		end;
	else
		l__Humanoid__3.WalkSpeed = l__Stats__5.Speed.Value;
		return;
	end;
	u38 = 0;
end;
function DirectionRayIgnoreCheck(p31, p32)
	if p31 then
		if p31.Name == "Glass" then

		elseif p31.Name == "Averter" then
			return true;
		else
			return false;
		end;
	else
		return false;
	end;
	if (p31.Position - l__Torso__4.Position).magnitude < u8 * 1.5 then
		if checkSight(p32) then
			onFireNormal(l__Head__23, p31);
		end;
	end;
	return true;
end;
function DirectionRayCast(p33, p34, p35)
	local v98, v99 = workspace:FindPartOnRay(Ray.new(p33, p34 * p35), l__Value__1);
	if v98 then
		if v99 then
			local v100 = p35 - (v99 - p33).magnitude;
			if DirectionRayIgnoreCheck(v98, v99) then
				if 0 < v100 then
					--return DirectionRayCast(v99, p34, v100);
				end;
			end;
		end;
	end;
	return v98, v99;
end;
function checkSight(p36)
	local v101 = Instance.new("Part");
	v101.Name = "Sight1";
	v101.Size = Vector3.new(1, 1, 1);
	v101.CanCollide = false;
	v101.Transparency = 1;
	local v102 = Instance.new("Weld");
	v102.Parent = l__Torso__4;
	v102.Part0 = l__Torso__4;
	v102.Part1 = v101;
	v102.C1 = v102.C1 + Vector3.new(16, 0, 12);
	v101.Parent = l__Value__1;
	local v103 = Instance.new("Part");
	v103.Name = "Sight2";
	v103.Size = Vector3.new(1, 1, 1);
	v103.CanCollide = false;
	v103.Transparency = 1;
	local v104 = Instance.new("Weld");
	v104.Parent = l__Torso__4;
	v104.Part0 = l__Torso__4;
	v104.Part1 = v103;
	v104.C1 = v104.C1 + Vector3.new(-16, 0, 12);
	v103.Parent = l__Value__1;
	local v105 = v101.Position - l__Torso__4.Position;
	local v106 = v103.Position - l__Torso__4.Position;
	local v107 = math.acos((v105.X * v106.X + v105.Y * v106.Y + v105.Z * v106.Z) / (v105.magnitude * v106.magnitude + 0.001));
	local v108 = Vector3.new(p36.X, 0, p36.Z) - l__Torso__4.Position;
	local v109 = v101.Position - l__Torso__4.Position;
	local v110 = math.acos((v108.X * v109.X + v108.Y * v109.Y + v108.Z * v109.Z) / (v108.magnitude * v109.magnitude + 0.001));
	local v111 = Vector3.new(p36.X, 0, p36.Z) - l__Torso__4.Position;
	local v112 = v103.Position - l__Torso__4.Position;
	local v113 = math.acos((v111.X * v112.X + v111.Y * v112.Y + v111.Z * v112.Z) / (v111.magnitude * v112.magnitude + 0.001));
	v101:Destroy();
	v102:Destroy();
	v103:Destroy();
	v104:Destroy();
	if v110 < v107 then
		if v113 < v107 then
			return true;
		end;
	end;
	return false;
end;
local u39 = nil;
local u40 = 0;
local l__Value__41 = l__Stats__5.Agressive.Value;
function findNearestTorso(p37)
	local v114 = l__CurrentCamera__1:getChildren();
	if l__CurrentCamera__1:findFirstChild("Level") then
		if l__CurrentCamera__1.Level:findFirstChild("NPC") then
			local npcs = l__CurrentCamera__1.Level.NPC:getChildren();
			
			for _, thing in npcs do
				if thing:IsA("Model") and thing:FindFirstChild("Humanoid") then
					if thing:FindFirstChild("MainControlVRT") then
						table.insert(npcs, thing)
					end
				end
			end
		end;
	end;
	local v117 = #v114;
	local v118 = 1 - 1;
	while true do
		if v114[v118] then
			if v114[v118]:IsA("Model") then
				if v114[v118] ~= l__Value__1 then
					if not l__Value__41 then
						if l__UnderAttack__36.Value then
							local v119 = v114[v118]:findFirstChild("Torso");
							local v120 = v114[v118]:findFirstChild("Humanoid");
							if v119 then
								if v120 then
									if not v114[v118]:findFirstChild("MainControlNPC") then
										if (v119.Position - p37).magnitude <= l__Value__11 then
											if 0 < v120.Health then
												if math.abs(v119.Position.Y - p37.Y) < 16 then
													local v121, v122 = DirectionRayCast(p37, (v119.Position - p37).unit, l__Value__11);
													local v123 = false;
													if v121 then
														if v121:IsDescendantOf(v114[v118]) then
															v123 = true;
														end;
													end;
													if not v123 then
														if l__UnderAttack__36.Value then
															if u39 then
																if v123 then
																	if (v119.Position - p37).magnitude < (u39.Position - p37).magnitude then
																		u40 = 10;
																		u39 = v119;
																	elseif v119 == u39 then
																		u40 = 10;
																	end;
																elseif not l__UnderAttack__36.Value then
																	if (v119.Position - p37).magnitude < 4 then
																		u40 = 10;
																		u39 = v119;
																	elseif checkSight(v122) then
																		u40 = 10;
																		u39 = v119;
																	end;
																else
																	u40 = 10;
																	u39 = v119;
																end;
															elseif not l__UnderAttack__36.Value then
																if (v119.Position - p37).magnitude < 4 then
																	u40 = 10;
																	u39 = v119;
																elseif checkSight(v122) then
																	u40 = 10;
																	u39 = v119;
																end;
															else
																u40 = 10;
																u39 = v119;
															end;
														elseif v119 == u39 then
															if u39 then
																u40 = u40 - 1;
																if u40 < -10 then
																	u39 = nil;
																	l__UnderAttack__36.Value = false;
																elseif u40 == 0 then
																	calculatePacing();
																end;
															end;
														end;
													elseif u39 then
														if v123 then
															if (v119.Position - p37).magnitude < (u39.Position - p37).magnitude then
																u40 = 10;
																u39 = v119;
															elseif v119 == u39 then
																u40 = 10;
															end;
														elseif not l__UnderAttack__36.Value then
															if (v119.Position - p37).magnitude < 4 then
																u40 = 10;
																u39 = v119;
															elseif checkSight(v122) then
																u40 = 10;
																u39 = v119;
															end;
														else
															u40 = 10;
															u39 = v119;
														end;
													elseif not l__UnderAttack__36.Value then
														if (v119.Position - p37).magnitude < 4 then
															u40 = 10;
															u39 = v119;
														elseif checkSight(v122) then
															u40 = 10;
															u39 = v119;
														end;
													else
														u40 = 10;
														u39 = v119;
													end;
												end;
											end;
										end;
									end;
								end;
							end;
						end;
					else
						local v119 = v114[v118]:findFirstChild("Torso");
						local v120 = v114[v118]:findFirstChild("Humanoid");
						if v119 then
							if v120 then
								if not v114[v118]:findFirstChild("MainControlNPC") then
									if (v119.Position - p37).magnitude <= l__Value__11 then
										if 0 < v120.Health then
											if math.abs(v119.Position.Y - p37.Y) < 16 then
												local v121, v122 = DirectionRayCast(p37, (v119.Position - p37).unit, l__Value__11);
												local v123 = false;
												if v121 then
													if v121:IsDescendantOf(v114[v118]) then
														v123 = true;
													end;
												end;
												if not v123 then
													if l__UnderAttack__36.Value then
														if u39 then
															if v123 then
																if (v119.Position - p37).magnitude < (u39.Position - p37).magnitude then
																	u40 = 10;
																	u39 = v119;
																elseif v119 == u39 then
																	u40 = 10;
																end;
															elseif not l__UnderAttack__36.Value then
																if (v119.Position - p37).magnitude < 4 then
																	u40 = 10;
																	u39 = v119;
																elseif checkSight(v122) then
																	u40 = 10;
																	u39 = v119;
																end;
															else
																u40 = 10;
																u39 = v119;
															end;
														elseif not l__UnderAttack__36.Value then
															if (v119.Position - p37).magnitude < 4 then
																u40 = 10;
																u39 = v119;
															elseif checkSight(v122) then
																u40 = 10;
																u39 = v119;
															end;
														else
															u40 = 10;
															u39 = v119;
														end;
													elseif v119 == u39 then
														if u39 then
															u40 = u40 - 1;
															if u40 < -10 then
																u39 = nil;
																l__UnderAttack__36.Value = false;
															elseif u40 == 0 then
																calculatePacing();
															end;
														end;
													end;
												elseif u39 then
													if v123 then
														if (v119.Position - p37).magnitude < (u39.Position - p37).magnitude then
															u40 = 10;
															u39 = v119;
														elseif v119 == u39 then
															u40 = 10;
														end;
													elseif not l__UnderAttack__36.Value then
														if (v119.Position - p37).magnitude < 4 then
															u40 = 10;
															u39 = v119;
														elseif checkSight(v122) then
															u40 = 10;
															u39 = v119;
														end;
													else
														u40 = 10;
														u39 = v119;
													end;
												elseif not l__UnderAttack__36.Value then
													if (v119.Position - p37).magnitude < 4 then
														u40 = 10;
														u39 = v119;
													elseif checkSight(v122) then
														u40 = 10;
														u39 = v119;
													end;
												else
													u40 = 10;
													u39 = v119;
												end;
											end;
										end;
									end;
								end;
							end;
						end;
					end;
				end;
			end;
		end;
		if 0 <= 1 then
			if v118 < v117 then

			else
				break;
			end;
		elseif v117 < v118 then

		else
			break;
		end;
		v118 = v118 + 1;	
	end;
end;
local u42 = false;
function checkAmmo()
	if l__Stats__5.Ammo.Value < 1 then
		u42 = true;
		l__Humanoid__3.WalkSpeed = 0;
		l__Stats__5.Tool.Value = "None";
		waitTime(1);
		l__Stats__5.Tool.Value = l__Stats__5.Tool.Value;
		l__Humanoid__3.WalkSpeed = l__Stats__5.Speed.Value;
		u42 = false;
	end;
end;
l__Stats__5.Ammo.Changed:connect(function()
	checkAmmo();
end);
local u43 = nil;
local u44 = false;
function calculatePacing()
	if not u39 then
		if v14 then
			v96.CFrame = CFrame.new(l__Path__13[tostring(l__Path__13.Value)].Value);
			l__Path__13.Value = l__Path__13.Value + 1;
			if #v15 < l__Path__13.Value then
				l__Path__13.Value = 1;
			end;
		elseif not u44 then
			u44 = true;
			if game.Players.LocalPlayer.Character:FindFirstChild("Torso") then

			else
				print("ERROR: No enemy found.");
				return;
			end;
			local u45 = (function(p38, p39)
				local v124 = game:GetService("PathfindingService"):ComputeRawPathAsync(p39, p38, 500);
				if v124.Status ~= Enum.PathStatus.FailStartNotEmpty then
					if v124.Status == Enum.PathStatus.FailFinishNotEmpty then

					else
						return v124:GetPointCoordinates();
					end;
				end;
				print("Compute failed");
				return {};
			end)(game.Players.LocalPlayer.Character.Torso.Position, l__Torso__4.Position);
			coroutine.resume(coroutine.create(function()
				local v125 = #u45;
				local v126 = 1 - 1;
				while true do
					v96.CFrame = CFrame.new(u45[v126]);
					local v127 = false;
					local v128 = #u45;
					local v129 = v126 - 1;
					while true do
						if (u45[v129] - l__Torso__4.Position).magnitude < 4 then
							if v126 < v129 then
								v127 = true;
								break;
							end;
						end;
						if 0 <= 1 then
							if v129 < v128 then

							else
								break;
							end;
						elseif v128 < v129 then

						else
							break;
						end;
						v129 = v129 + 1;					
					end;
					if not v127 then
						if l__Torso__4.Position.y + 2 < u45[v126].y then
							l__Humanoid__3.Jump = true;
						end;
						local v130 = 0;
						while true do
							v130 = v130 + 1;
							local v131 = (u45[v126] - l__Torso__4.Position).magnitude;
							if v130 % 32 == 0 then
								l__Humanoid__3.Jump = true;
							elseif 72 < v130 then
								v131 = 0;
							end;
							waitTime(1);
							if not (v131 < 3) then

							else
								break;
							end;
							if u44 then

							else
								break;
							end;						
						end;
						if u44 then

						else
							break;
						end;
					end;
					if 0 <= 1 then
						if v126 < v125 then

						else
							break;
						end;
					elseif v125 < v126 then

					else
						break;
					end;
					v126 = v126 + 1;				
				end;
				u44 = false;
			end));
		end;
	else
		v96.CFrame = CFrame.new(u39.Position) + Vector3.new(12 * (math.random(0, 1) * 2 - 1), 0, 12 * (math.random(0, 1) * 2 - 1));
	end;
	u43 = v96;
end;
function enemyLost()
	if not l__Stats__5.Mode.Value then
		l__Stats__5.Mode.Value = true;
	end;
	if u38 <= 0 then
		if v14 then
			if #v15 <= 1 then
				if u43 then
					if (u43.Position - l__Torso__4.Position).magnitude < 3 then
						u26 = "Standing";
					else
						u26 = "Pacing";
					end;
				else
					u26 = "Pacing";
				end;
			else
				u26 = "Pacing";
			end;
		else
			u26 = "Pacing";
		end;
		u38 = 60;
		calculatePacing();
		return;
	end;
	if v14 then
		if #v15 <= 1 then
			if u43 then
				if (u43.Position - l__Torso__4.Position).magnitude < 3 then
					u26 = "Standing";
				else
					u26 = "Pacing";
				end;
			else
				u26 = "Pacing";
			end;
		else
			u26 = "Pacing";
		end;
	else
		u26 = "Pacing";
	end;
	u38 = u38 - 1;
end;
l__Stats__5.EnemyFound.Changed:connect(function()
	if not l__Stats__5.EnemyFound.Value then
		u38 = 12;
		u26 = "Standing";
		u43 = nil;
		enemyLost();
	end;
end);
local u46 = l__Stats__5.OffsetMaxX.Value + l__Torso__4.Position.X;
local u47 = l__Stats__5.OffsetMaxZ.Value + l__Torso__4.Position.Z;
local u48 = l__Stats__5.OffsetMinX.Value + l__Torso__4.Position.X;
local u49 = l__Stats__5.OffsetMinZ.Value + l__Torso__4.Position.Z;
local u50 = l__Torso__4["Right Hip"];
local u51 = l__Torso__4["Left Hip"];
function move(p40)
	local v132 = 0
	local v133 = 0
	
	if u26 ~= "Following" then
		if u26 == "Pacing" then
			if 0 < l__Humanoid__3.WalkSpeed then
				if not (1.5 < u50.CurrentAngle) then
					if u50.CurrentAngle < -1.5 then
						u50.MaxVelocity = 0.75;
					else
						u50.MaxVelocity = 0.15;
					end;
				else
					u50.MaxVelocity = 0.75;
				end;
				if not (1.5 < u51.CurrentAngle) then
					if u51.CurrentAngle < -1.5 then
						u51.MaxVelocity = 0.75;
					else
						u51.MaxVelocity = 0.15;
					end;
				else
					u51.MaxVelocity = 0.75;
				end;
				v132 = 1;
				v133 = 9;
			else
				v132 = 0.1;
				v133 = 1;
			end;
		else
			v132 = 0.1;
			v133 = 1;
		end;
	elseif 0 < l__Humanoid__3.WalkSpeed then
		if not (1.5 < u50.CurrentAngle) then
			if u50.CurrentAngle < -1.5 then
				u50.MaxVelocity = 0.75;
			else
				u50.MaxVelocity = 0.15;
			end;
		else
			u50.MaxVelocity = 0.75;
		end;
		if not (1.5 < u51.CurrentAngle) then
			if u51.CurrentAngle < -1.5 then
				u51.MaxVelocity = 0.75;
			else
				u51.MaxVelocity = 0.15;
			end;
		else
			u51.MaxVelocity = 0.75;
		end;
		v132 = 1;
		v133 = 9;
	else
		v132 = 0.1;
		v133 = 1;
	end;
	
	local v134 = v132 * math.sin(p40 * v133);
	u50:SetDesiredAngle(-v134);
	u51:SetDesiredAngle(-v134);
end;
local function u52()
	u26 = "Following";
	if u40 >= 0 then
		u43 = u39;
	end;
	local l__magnitude__135 = (u39.Position - l__Torso__4.Position).magnitude;
	if u27 and not u42 and l__magnitude__135 < u8 and not u4 and checkSight(u39.Position) and u39.Parent:findFirstChild("Humanoid") and (u39.Parent.Humanoid.Health > 0 or u39.Parent.Humanoid.MaxHealth == 0) then
		if l__Stats__5.Mode.Value and u28 and l__Stats__5.Ammo.Value > 0 and l__Value__1.Name ~= "Repressilator" then
			coroutine.resume(coroutine.create(function()
				onFireNormal(u28, u39);
			end));
			l__Stats__5.Ammo.Value = l__Stats__5.Ammo.Value - 1;
		elseif not l__Stats__5.Mode.Value then
			if l__Value__1.Name ~= "Repressilator" then
				local l__unit__136 = l__Head__23.CFrame.lookVector.unit;
				l__Torso__4.Velocity = Vector3.new(l__magnitude__135 * 7 * l__unit__136.x, l__Torso__4.Velocity.y, l__magnitude__135 * 7 * l__unit__136.z);
			end;
			coroutine.resume(coroutine.create(function()
				fists(math.random(1, 2));
			end));
		elseif l__Value__1.Name == "Repressilator" then
			coroutine.resume(coroutine.create(function()
				laserBall(l__Torso__4, u39);
			end));
		end;
	elseif l__Value__11 < l__magnitude__135 and u37 == 0 then
		if u39 then
			u40 = u40 - 1;
			if u40 < -10 then
				u39 = nil;
				l__UnderAttack__36.Value = false;
			elseif u40 == 0 then
				calculatePacing();
			end;
		end;
	elseif u39.Parent.Humanoid.Health < 1 and u39.Parent.Humanoid.MaxHealth ~= 0 then
		u39 = nil;
	end;
	if l__magnitude__135 < 10 then
		l__Stats__5.Mode.Value = false;
		if l__Value__1.Name ~= "Repressilator" then
			return;
		end;
	else
		l__Stats__5.Mode.Value = true;
		return;
	end;
	local l__unit__137 = l__Head__23.CFrame.lookVector.unit;
	l__Torso__4.Velocity = Vector3.new(l__magnitude__135 * -6 * l__unit__137.x, l__Torso__4.Velocity.y + 10, l__magnitude__135 * -6 * l__unit__137.z);
end;
local function u53(p41)
	local v140, v146 = 0, 0
	
	if u46 < l__Torso__4.Position.X or u47 < l__Torso__4.Position.Z or l__Torso__4.Position.X < u48 or l__Torso__4.Position.Z < u49 then
		if v14 then
			v96.CFrame = CFrame.new(l__Path__13[tostring(l__Path__13.Value)].Value);
			p41 = v96;
			u38 = 60;
			local v138, v139 = DirectionRayCast(l__Torso__4.Position, (v96.Position - l__Torso__4.Position).unit, l__Value__11);
			v140 = v138;
		else
			v96.CFrame = CFrame.new((u46 + u48) / 2, l__Torso__4.Position.Y, (u47 + u49) / 2);
			p41 = v96;
			u38 = 80;
			local v141, v142 = DirectionRayCast(l__Torso__4.Position, (v96.Position - l__Torso__4.Position).unit, l__Value__11);
			v140 = v141;
		end;
		if v140 and not v14 then
			wait();
			if math.random(1, 2) % 2 then
				local v143 = (u47 + u49) / 2;
				v96.CFrame = CFrame.new(l__Torso__4.Position.X, l__Torso__4.Position.Y, math.random(v143 - 4, v143 + 4));
				p41 = v96;
				local v144, v145 = DirectionRayCast(l__Torso__4.Position, (v96.Position - l__Torso__4.Position).unit, l__Value__11);
				v146 = v144;
			else
				local v147 = (u46 + u48) / 2;
				v96.CFrame = CFrame.new(math.random(v147 - 4, v147 + 4), l__Torso__4.Position.Y, l__Torso__4.Position.Z);
				p41 = v96;
				local v148, v149 = DirectionRayCast(l__Torso__4.Position, (v96.Position - l__Torso__4.Position).unit, l__Value__11);
				v146 = v148;
			end;
			if v146 then
				v96.CFrame = CFrame.new((u46 + u48) / 2, l__Torso__4.Position.Y, (u47 + u49) / 2);
				p41 = v96;
			end;
		end;
	end;
	l__Humanoid__3:MoveTo(p41.Position, p41);
end;
function runBot(p42)
	local v150 = nil;
	move(p42);
	if 0 < l__Humanoid__3.Health then

	else
		u26 = "Standing";
		u43 = nil;
		return;
	end;
	u37 = u37 + 1;
	if 9 < u37 then
		u37 = 0;
		findNearestTorso(l__Torso__4.Position);
	end;
	if u39 then
		l__Stats__5.State.Value = 2;
		l__Stats__5.EnemyFound.Value = true;
		u44 = false;
		u52();
	else
		if l__Value__41 then
			l__Stats__5.State.Value = 1;
		else
			l__Stats__5.State.Value = 0;
		end;
		if l__Stats__5.EnemyFound.Value then
			l__Stats__5.EnemyFound.Value = false;
		else
			enemyLost();
		end;
	end;
	if u43 then
		u53(u43);
		followEnemy(u43);
	else
		u53(l__Torso__4);
	end;
	updateAim();
	if not u33 then
		if u34 then
			u35 = u35 + 1;
		end;
	else
		u35 = u35 + 1;
	end;
	if 10 < u35 then
		l__UnderAttack__36.Value = true;
	end;
	local v151, v152, v153 = l__Torso__4.CFrame:toEulerAnglesXYZ();
	v150 = math.deg(v152 + math.pi / 2);
	
	local v154
	
	if 0 < l__Torso__4.CFrame.lookVector.Z then
		v154 = v150 + 180;
	else
		v154 = 180 - v150;
	end;
	
	l__Stats__5.RadarRotation.Value = math.ceil(v154 + 180);
end;
if l__Stats__5.WaitTime.Value > 0 then
	wait(l__Stats__5.WaitTime.Value);
end;
while l__Value__1 and l__Value__1.Parent do
	local v155, v156 = wait();
	if not l__Value__1 then
		break;
	end;
	if not l__Value__1.Parent then
		break;
	end;
	if script.Parent:findFirstChild("LocalScript") and script.Parent.LocalScript:findFirstChild("LocalPause") then
		if not script.Parent.LocalScript.LocalPause.Value or l__CurrentCamera__1.CameraType == "Scriptable" then
			if l__Humanoid__3.WalkSpeed == 0 then
				l__Humanoid__3.WalkSpeed = l__Stats__5.Speed.Value;
			end;
			runBot(v156);
			for v157 = 1, 3 do
				wait();
				if not l__Value__1 then
					break;
				end;
				if not l__Value__1.Parent then
					break;
				end;
				updateAim();
			end;
		elseif l__Humanoid__3.WalkSpeed ~= 0 then
			l__Humanoid__3.WalkSpeed = 0;
		end;
	else
		runBot(v156);
	end;
end;
script:Destroy();
