-- Decompiled with the Synapse X Luau decompiler.

print("Running MegaBot Script");

task.wait(1.2)

local l__Value__1 = script.LinkedModel.Value;
local l__Debris__2 = game:GetService("Debris");
local l__Humanoid__3 = l__Value__1.Humanoid;

game:GetService("ScriptContext").Error:Connect(function(Error, trace, erroredScript)
	if erroredScript == script then
		warn("Error generated by: " .. l__Humanoid__3.Parent.Name)
		warn(Error)
	end
end)


local l__Torso__4 = l__Value__1.Torso;
local l__Stats__5 = l__Value__1.Stats;
local v6 = require(workspace.CFrameInterpolator);
local l__RightHip__7 = l__Value__1.Main.Hips.RightHip;
local l__LeftHip__8 = l__Value__1.Main.Hips.LeftHip;
local l__Weld__9 = l__Value__1.RightLeg.Section1.Knee.Weld;
local l__Weld__10 = l__Value__1.LeftLeg.Section1.Knee.Weld;
local l__RightShoulder__11 = l__Torso__4.RightShoulder;
local l__LeftShoulder__12 = l__Torso__4.LeftShoulder;
playerStats = game.Players.LocalPlayer.Stats
l__Humanoid__3.MaxHealth = l__Stats__5.Health.Value * (playerStats.Difficulty.Value / 3);
l__Humanoid__3.Health = l__Humanoid__3.MaxHealth;
l__Humanoid__3.WalkSpeed = l__Stats__5.Speed.Value;
local l__Value__13 = l__Stats__5.Range.Value;
local v14 = math.random(0, 1);
local l__Path__15 = l__Stats__5.Path;
local v16 = false;
local v17 = l__Path__15:GetChildren();
if #v17 > 0 then
	v16 = true;
end;
l__Humanoid__3.AutoRotate = false;

local v18 = l__Torso__4:findFirstChild("BodyGyro");

if not v18 then
	v18 = Instance.new("BodyGyro");
	v18.P = 3000;
	v18.D = 700;
	v18.maxTorque = Vector3.new(math.huge, math.huge, math.huge);
	v18.cframe = l__Torso__4.CFrame;
	v18.Parent = l__Torso__4;
end;

function unanchor(p1)
	local v19 = p1:GetChildren();
	local v20 = #v19;
	local v21 = 1 - 1;
	while true do
		if v19[v21] then
			if v19[v21]:IsA("Part") then
				v19[v21].Anchored = false;
			elseif v19[v21] then
				if v19[v21]:IsA("Model") then
					unanchor(v19[v21]);
				end;
			end;
		elseif v19[v21] then
			if v19[v21]:IsA("Model") then
				unanchor(v19[v21]);
			end;
		end;
		if 0 <= 1 then
			if v21 < v20 then

			else
				break;
			end;
		elseif v20 < v21 then

		else
			break;
		end;
		v21 = v21 + 1;	
	end;
end;
unanchor(l__Value__1);

function waitTime(p5)
	for i = 0, p5 do
		task.wait(0.03)
		if script.Parent.GamePause.Value then
			script.Parent.GamePause.Changed:Wait()
		end
	end
end;

local l__CurrentCamera__1 = workspace.CurrentCamera;

l__Humanoid__3.Died:connect(function()
	checkDamage();
	
	coroutine.resume(coroutine.create(function()
		waitTime(4000);
		l__Value__1:Destroy();
		script:Destroy();
	end));
	
	waitTime(1);
	
	if l__Value__1:findFirstChild("Torso") and l__Torso__4.Position.y > 0 then
		local v23 = Instance.new("Explosion");
		v23.Position = l__Torso__4.Position;
		v23.BlastPressure = 0;
		v23.BlastRadius = 10;
		v23.Parent = l__CurrentCamera__1;
		l__Debris__2:AddItem(v23, 3);
		l__Value__1:BreakJoints();
		if script.Parent:FindFirstChild("SoundScript") then
			local v24 = Instance.new("StringValue");
			v24.Name = "Sound";
			v24.Value = "RoboticExplosion";
			local v25 = Instance.new("ObjectValue");
			v25.Name = "Location";
			v25.Value = l__Torso__4;
			v25.Parent = v24;
			v24.Parent = script.Parent.SoundScript.Effects;
		end;
		if l__Stats__5.Counter.Value then
			l__Stats__5.Counter.Value.Value = l__Stats__5.Counter.Value.Value - 1;
		end;
		--script.LinkedModel.Value = nil;
		--waitTime(5000);
		--script:Destroy();
	end;
end);
local u2 = false;
l__Humanoid__3.ChildAdded:connect(function()
	if l__Humanoid__3:findFirstChild("creator") and not u2 then
		u2 = true;
	end;
end);
l__Humanoid__3.ChildRemoved:connect(function()
	if not l__Humanoid__3:findFirstChild("creator") and u2 then
		u2 = false;
	end;
end);
local l__GameItems__3 = game.ReplicatedStorage.GameItems;
function visualDamage(p3, p4, p5)
	local v26 = Instance.new("BillboardGui");
	v26.Size = UDim2.new(1, 0, 1, 0);
	v26.StudsOffset = Vector3.new(math.random(-1, 1), 1.65, math.random(-1, 1));
	local v27 = l__GameItems__3.MasterGuis.DamageFrame:clone();
	v27.Parent = v26;
	if p4 == 0 then
		v27.TextLabel.Text = "-" .. p4;
		v27.TextLabel.TextStrokeColor3 = Color3.new(0, 0, 1);
	elseif p4 < 0 then
		v27.TextLabel.Text = "+" .. p4;
		v27.TextLabel.TextStrokeColor3 = Color3.new(0, 1, 0);
	else
		v27.TextLabel.Text = "-" .. p4;
		v27.TextLabel.TextStrokeColor3 = Color3.new(1, 0, 0);
	end;
	v26.Parent = p5;
	v26.Adornee = p5;
	local l__BillboardControl__28 = v27.BillboardControl;
	l__BillboardControl__28.Billboard.Value = v26;
	l__BillboardControl__28.Parent = script.Parent;
	l__BillboardControl__28.Disabled = false;
	l__Debris__2:AddItem(v26, 5);
end;
local function u4(p6)
	local l__X__29 = p6.Position.X;
	local l__Y__30 = p6.Position.Y;
	local l__Z__31 = p6.Position.Z;
	local l__X__32 = p6.Size.X;
	local l__Y__33 = p6.Size.Y;
	local l__Z__34 = p6.Size.Z;
	local v35 = p6.CFrame - p6.CFrame.p;
	p6:Destroy();
	local v36 = Instance.new("Part");
	v36.Name = "Averter";
	v36.FormFactor = 0;
	v36.Size = Vector3.new(1, 1, 1);
	v36.BrickColor = p6.BrickColor;
	v36.Shape = 1;
	v36.BottomSurface = 0;
	v36.TopSurface = 0;
	v36.Reflectance = p6.Reflectance;
	v36.Transparency = p6.Transparency;
	v36.CanCollide = false;
	for v37 = 0, l__X__32 - 1 do
		for v38 = 0, l__Y__33 - 1 do
			for v39 = 0, l__Z__34 - 1 do
				local v40 = v36:clone();
				v40.Velocity = Vector3.new(math.random(-20, 20), math.random(-20, 20), math.random(-20, 20));
				v40.CFrame = CFrame.new(l__X__29 - (l__X__32 - 1) / 2 + v37, l__Y__30 - (l__Y__33 - 1) / 2 + v38, l__Z__31 - (l__Z__34 - 1) / 2 + v39) * v35;
				l__Debris__2:AddItem(v40, 0.5);
				v40.Parent = l__CurrentCamera__1;
			end;
		end;
	end;
end;
function normalDamage(p7, p8)
	local v41 = p7.Parent:findFirstChild("Humanoid") or p7.Parent.Parent:findFirstChild("Humanoid");
	if v41 then
		if not game.Players:findFirstChild(v41.Parent.Name) then
			if v41.Parent:findFirstChild("MainControlVRT") then
				if 0 < v41.Health then
					if not v41.Parent:findFirstChild("ForceField") then
						if v41.Parent:findFirstChild("Head") then
							local v42 = math.ceil(p8 * playerStats.Difficulty.Value / 3);
							print(v42);
							if p7.Name == "Head" then
								v42 = math.ceil(v42 * 2);
							elseif p7.Name == "Torso" then
								v42 = math.ceil(v42 * 1.5);
							end;
							v41:TakeDamage(v42);
							visualDamage(v41, v42, v41.Parent.Head);
							return;
						end;
					end;
				end;
			else
				if p7.Name == "Glass" then
					u4(p7);
					return;
				end;
				if p7.Name == "Explosive" then
					if p7:findFirstChild("Explode") then
						p7.Explode.Value = true;
					end;
				end;
			end;
		elseif 0 < v41.Health then
			if not v41.Parent:findFirstChild("ForceField") then
				if v41.Parent:findFirstChild("Head") then
					local v42 = math.ceil(p8 * playerStats.Difficulty.Value / 3);
					print(v42);
					if p7.Name == "Head" then
						v42 = math.ceil(v42 * 2);
					elseif p7.Name == "Torso" then
						v42 = math.ceil(v42 * 1.5);
					end;
					v41:TakeDamage(v42);
					visualDamage(v41, v42, v41.Parent.Head);
					return;
				end;
			end;
		end;
	else
		if p7.Name == "Glass" then
			u4(p7);
			return;
		end;
		if p7.Name == "Explosive" then
			if p7:findFirstChild("Explode") then
				p7.Explode.Value = true;
			end;
		end;
	end;
end;
local v43 = Instance.new("Part");
v43.FormFactor = Enum.FormFactor.Custom;
v43.Size = Vector3.new(0.2, 0.2, 1);
v43.BrickColor = BrickColor.new("Bright red");
v43.CanCollide = false;
v43.Anchored = true;
v43.Transparency = 0.3;
v43.TopSurface = Enum.SurfaceType.Smooth;
v43.BottomSurface = Enum.SurfaceType.Smooth;
v43.Name = "Averter";
function RayIgnoreCheck(p9, p10)
	if p9 then
		if not (1 <= p9.Transparency) then
			if string.lower(p9.Name) ~= "water" then
				if p9.Name ~= "Effect" then
					if p9.Name ~= "Rocket" then
						if p9.Name ~= "Averter" then
							if p9.Parent.ClassName ~= "Hat" then
								if p9.Parent.ClassName == "Tool" then

								else
									return false;
								end;
							end;
						end;
					end;
				end;
			end;
		end;
	else
		return false;
	end;
	return true;
end;
function RayCast(p11, p12, p13)
	local v44, v45 = workspace:FindPartOnRay(Ray.new(p11 + p12 * 0.01, p12 * p13), l__Value__1);
	if v44 then
		if v45 then
			local v46 = p13 - (v45 - p11).magnitude;
			if RayIgnoreCheck(v44, v45) then
				if 0 < v46 then
					return RayCast(v45, p12, v46);
				end;
			end;
		end;
	end;
	return v44, v45;
end;
local l__Head__5 = l__Value__1.Head;
local u6 = l__Value__13 / 2;
function onFireNormal(p14, p15)
	if p14 == l__Head__5 then
		local v47 = Instance.new("Part");
		v47.FormFactor = Enum.FormFactor.Symmetric;
		v47.Size = Vector3.new(1, 1, 1);
		v47.BrickColor = BrickColor.new("Bright red");
		v47.CanCollide = false;
		v47.Transparency = 0.3;
		v47.TopSurface = Enum.SurfaceType.Smooth;
		v47.BottomSurface = Enum.SurfaceType.Smooth;
		v47.Name = "Averter";
		local v48 = Instance.new("SpecialMesh");
		v48.MeshType = "Sphere";
		v48.Scale = Vector3.new(0, 0, 0);
		v48.Parent = v47;
		local v49 = Instance.new("Weld");
		v49.Parent = l__Head__5;
		v49.Part0 = l__Head__5;
		v49.Part1 = v47;
		v47.Parent = l__Value__1;
		v49.C1 = CFrame.new(v49.C1.p) + Vector3.new(0, 0.5, 2);
		local v50 = 1 - 1;
		while true do
			local v51, v52 = wait();
			move(v52);
			v48.Scale = Vector3.new(v50 * 0.07, v50 * 0.07, v50 * 0.07);
			if 0 <= 1 then
				if v50 < 16 then

				else
					break;
				end;
			elseif 16 < v50 then

			else
				break;
			end;
			v50 = v50 + 1;		
		end;
		local v53 = 16 - -2;
		while true do
			local v54, v55 = wait();
			move(v55);
			v48.Scale = Vector3.new(v53 * 0.07, v53 * 0.07, v53 * 0.07);
			if 0 <= -2 then
				if v53 < 8 then

				else
					break;
				end;
			elseif 8 < v53 then

			else
				break;
			end;
			v53 = v53 + -2;		
		end;
		v49:Destroy();
		v47:Destroy();
	end;
	local v56 = (p15.Position - p14.Position).unit;
	if p15.Name ~= "Glass" then
		v56 = (CFrame.new(Vector3.new(0, 0, 0), v56) * CFrame.Angles(0, 0, math.random() * 2 * math.pi) * CFrame.Angles(math.random() * 0.2, 0, 0)).lookVector;
	end;
	local v57, v58 = RayCast(p14.Position, v56, u6);
	if script.Parent:FindFirstChild("SoundScript") then
		local v59 = Instance.new("StringValue");
		v59.Name = "Sound";
		v59.Value = "LaserShot";
		local v60 = Instance.new("ObjectValue");
		v60.Name = "Location";
		v60.Value = l__Torso__4;
		v60.Parent = v59;
		v59.Parent = script.Parent.SoundScript.Effects;
	end;
	if v58 then
		local v61 = v43:clone();
		if p14 == l__Head__5 then
			v61.Size = Vector3.new(0.5, 0.5, 1);
		end;
		local l__magnitude__62 = (v58 - p14.Position).magnitude;
		v61.CFrame = CFrame.new(v58, p14.Position) * CFrame.new(0, 0, -l__magnitude__62 / 2);
		local v63 = Instance.new("BlockMesh");
		v63.Scale = Vector3.new(1, 1, l__magnitude__62 - 2);
		v63.Offset = Vector3.new(0, 0, 2);
		v63.Parent = v61;
		v61.Parent = l__CurrentCamera__1;
		l__Debris__2:AddItem(v61, 0.06);
	end;
	if v57 then
		if v57.Parent then
			if v58 then
				local v64 = 4;
				if p14 == l__Head__5 then
					v64 = v64 * 1.5;
				end;
				normalDamage(v57, v64);
			end;
		end;
	end;
end;
local u7 = false;
local l__C1__8 = l__LeftShoulder__12.C1;
local l__C1__9 = l__RightShoulder__11.C1;
local u10 = 0;
function checkAmmo()
	if l__Stats__5.Ammo.Value < 1 then
		u7 = true;
		l__Humanoid__3.WalkSpeed = 0;
		local v65, v66 = v6(l__LeftShoulder__12.C1, l__C1__8 * CFrame.Angles(1.5, 0, 0));
		local v67, v68 = v6(l__RightShoulder__11.C1, l__C1__9 * CFrame.Angles(1.5, 0, 0));
		local v69 = 1 - 1;
		while true do
			l__LeftShoulder__12.C1 = v66(v69 / 30);
			l__RightShoulder__11.C1 = v68(v69 / 30);
			waitTime(1);
			if 0 <= 1 then
				if v69 < 30 then

				else
					break;
				end;
			elseif 30 < v69 then

			else
				break;
			end;
			v69 = v69 + 1;		
		end;
		local v70 = 1 - 1;
		while true do
			l__RightShoulder__11.C1 = l__RightShoulder__11.C1 - Vector3.new(0, 0.2, 0);
			l__LeftShoulder__12.C1 = l__LeftShoulder__12.C1 - Vector3.new(0, 0.2, 0);
			waitTime(1);
			if 0 <= 1 then
				if v70 < 5 then

				else
					break;
				end;
			elseif 5 < v70 then

			else
				break;
			end;
			v70 = v70 + 1;		
		end;
		local v71 = 1 - 1;
		while true do
			l__RightShoulder__11.C1 = l__RightShoulder__11.C1 + Vector3.new(0, 0.2, 0);
			l__LeftShoulder__12.C1 = l__LeftShoulder__12.C1 + Vector3.new(0, 0.2, 0);
			waitTime(1);
			if 0 <= 1 then
				if v71 < 5 then

				else
					break;
				end;
			elseif 5 < v71 then

			else
				break;
			end;
			v71 = v71 + 1;		
		end;
		u10 = 0;
		local v72, v73 = v6(l__LeftShoulder__12.C1, l__C1__8 * CFrame.Angles(0, 0, 0));
		local v74, v75 = v6(l__RightShoulder__11.C1, l__C1__9 * CFrame.Angles(0, 0, 0));
		local v76 = 1 - 1;
		while true do
			l__LeftShoulder__12.C1 = v73(v76 / 30);
			l__RightShoulder__11.C1 = v75(v76 / 30);
			waitTime(1);
			if 0 <= 1 then
				if v76 < 30 then

				else
					break;
				end;
			elseif 30 < v76 then

			else
				break;
			end;
			v76 = v76 + 1;		
		end;
		l__Stats__5.Ammo.Value = l__Stats__5.MaxAmmo.Value;
		l__Humanoid__3.WalkSpeed = l__Stats__5.Speed.Value;
		u7 = false;
	end;
end;
l__Stats__5.Ammo.Changed:connect(function()
	checkAmmo();
end);


local v77 = Instance.new("Part");
v77.Name = "Home";
v77.Transparency = 1;
v77.CanCollide = false;
v77.Anchored = true;
v77.CFrame = l__Torso__4.CFrame;
v77.Parent = l__Value__1;

local u11 = "Pacing";
local u12 = 0;
function followEnemy(p16)
	if u7 then
		return;
	end;
	print(p16:GetFullName())
	
	v18.cframe = CFrame.new(l__Torso__4.Position, p16.Position)
	
	local v78 = (l__Head__5.Position.y - p16.Position.y) / (l__Head__5.Position - p16.Position).magnitude;
	if 0.02 < math.abs(v78 - u10) then
		if u10 < v78 then
			v78 = u10 + 0.02;
		else
			v78 = u10 - 0.02;
		end;
	end;
	u10 = v78;
	l__RightShoulder__11.C1 = l__C1__9 * CFrame.Angles(-v78, 0, 0);
	l__LeftShoulder__12.C1 = l__C1__8 * CFrame.Angles(-v78, 0, 0);
	local l__magnitude__79 = (p16.Position - l__Torso__4.Position).magnitude;
	if l__magnitude__79 < 10 then
		l__Humanoid__3.WalkSpeed = l__Stats__5.Speed.Value - (10 - l__magnitude__79) * (10 - l__magnitude__79) / (l__magnitude__79 * 100) * l__Stats__5.Speed.Value;
		if l__magnitude__79 < 5 then
			if u11 == "Pacing" then

			else
				return;
			end;
		else
			return;
		end;
	else
		l__Humanoid__3.WalkSpeed = l__Stats__5.Speed.Value;
		return;
	end;
	u12 = 0;
end;
function DirectionRayIgnoreCheck(p17, p18)
	if p17 then
		if p17.Name == "Glass" then

		elseif p17.Name == "Averter" then
			return true;
		else
			return false;
		end;
	else
		return false;
	end;
	if (p17.Position - l__Torso__4.Position).magnitude < u6 * 1.5 then
		if checkSight(p18) then
			onFireNormal(l__Head__5, p17);
		end;
	end;
	return true;
end;
function DirectionRayCast(p19, p20, p21)
	local v80, v81 = workspace:FindPartOnRay(Ray.new(p19, p20 * p21), l__Value__1);
	if v80 then
		if v81 then
			local v82 = p21 - (v81 - p19).magnitude;
			if DirectionRayIgnoreCheck(v80, v81) then
				if 0 < v82 then
					--return DirectionRayCast(v81, p20, v82);
				end;
			end;
		end;
	end;
	return v80, v81;
end;
function checkSight(p22)
	local v83 = Instance.new("Part");
	v83.Name = "Sight1";
	v83.Size = Vector3.new(1, 1, 1);
	v83.CanCollide = false;
	v83.Transparency = 1;
	local v84 = Instance.new("Weld");
	v84.Parent = l__Torso__4;
	v84.Part0 = l__Torso__4;
	v84.Part1 = v83;
	v84.C1 = v84.C1 + Vector3.new(16, 0, 12);
	v83.Parent = l__Value__1;
	local v85 = Instance.new("Part");
	v85.Name = "Sight2";
	v85.Size = Vector3.new(1, 1, 1);
	v85.CanCollide = false;
	v85.Transparency = 1;
	local v86 = Instance.new("Weld");
	v86.Parent = l__Torso__4;
	v86.Part0 = l__Torso__4;
	v86.Part1 = v85;
	v86.C1 = v86.C1 + Vector3.new(-16, 0, 12);
	v85.Parent = l__Value__1;
	local v87 = v83.Position - l__Torso__4.Position;
	local v88 = v85.Position - l__Torso__4.Position;
	local v89 = math.acos((v87.X * v88.X + v87.Y * v88.Y + v87.Z * v88.Z) / (v87.magnitude * v88.magnitude + 0.001));
	local v90 = Vector3.new(p22.X, 0, p22.Z) - l__Torso__4.Position;
	local v91 = v83.Position - l__Torso__4.Position;
	local v92 = math.acos((v90.X * v91.X + v90.Y * v91.Y + v90.Z * v91.Z) / (v90.magnitude * v91.magnitude + 0.001));
	local v93 = Vector3.new(p22.X, 0, p22.Z) - l__Torso__4.Position;
	local v94 = v85.Position - l__Torso__4.Position;
	local v95 = math.acos((v93.X * v94.X + v93.Y * v94.Y + v93.Z * v94.Z) / (v93.magnitude * v94.magnitude + 0.001));
	v83:Destroy();
	v84:Destroy();
	v85:Destroy();
	v86:Destroy();
	if v92 < v89 then
		if v95 < v89 then
			return true;
		end;
	end;
	return false;
end;
local u13 = nil;
local u14 = 0;
local function u15()
	if u13 then
		u14 = u14 - 1;
		print("Count Down 1: ", u14);
		if u14 < -40 then
			print(u14);
			u13 = nil;
			return;
		end;
		if u14 == 0 or u14 == -10 or u14 == -20 or u14 == -30 then
			print(u14);
			calculatePacing();
		end;
	end;
end;
function findNearestTorso(p23)
	local v96 = l__CurrentCamera__1:getChildren();
	if l__CurrentCamera__1:findFirstChild("Level") then
		if l__CurrentCamera__1.Level:findFirstChild("NPC") then
			local v97 = l__CurrentCamera__1.Level.NPC:getChildren();
			
			for _, thing in v97 do
				if thing:IsA("Model") and thing:FindFirstChild("Humanoid") then
					if thing:FindFirstChild("MainControlVRT") then
						table.insert(v97, thing)
					end
				end
			end
		end
	end;
	local v100 = #v96;
	local v101 = 1 - 1;
	while true do
		if v96[v101] then
			if v96[v101]:IsA("Model") then
				if v96[v101] ~= l__Value__1 then
					local v102 = v96[v101]:findFirstChild("Torso");
					local v103 = v96[v101]:findFirstChild("Humanoid");
					if v102 then
						if v103 then
							if not v96[v101]:findFirstChild("MainControlNPC") then
								if (v102.Position - p23).magnitude <= l__Value__13 then
									if p23.Y - 48 < v102.Position.Y then
										if 0 < v103.Health then
											local v104, v105 = DirectionRayCast(p23, (v102.Position - p23).unit, l__Value__13);
											if v104 then
												if v104:IsDescendantOf(v96[v101]) then
													if u13 then
														if (v102.Position - p23).magnitude < (u13.Position - p23).magnitude then
															u14 = 10;
															u13 = v102;
														elseif v102 == u13 then
															u14 = 10;
														end;
													elseif not u2 then
														if (v102.Position - p23).magnitude < 4 then
															u14 = 10;
															u13 = v102;
														elseif checkSight(v105) then
															u14 = 10;
															u13 = v102;
														end;
													else
														u14 = 10;
														u13 = v102;
													end;
												else
													u15();
												end;
											else
												u15();
											end;
										end;
									end;
								end;
							end;
						end;
					end;
				end;
			end;
		end;
		if 0 <= 1 then
			if v101 < v100 then

			else
				break;
			end;
		elseif v100 < v101 then

		else
			break;
		end;
		v101 = v101 + 1;	
	end;
end;
local u16 = nil;
local u17 = 0;
function calculatePacing()
	if not u13 then
		if v16 then
			v77.CFrame = CFrame.new(v17[l__Path__15.Value].Value);
			l__Path__15.Value = l__Path__15.Value + 1;
			if #v17 < l__Path__15.Value then
				l__Path__15.Value = 1;
			end;
		else
			v77.CFrame = CFrame.new(l__Torso__4.Position) + Vector3.new(math.random(-30, 30), 0, math.random(-30, 30));
		end;
	else
		v77.CFrame = CFrame.new(u13.Position) + Vector3.new(12 * (math.random(0, 1) * 2 - 1), 0, 12 * (math.random(0, 1) * 2 - 1));
	end;
	u16 = v77;
	local v106, v107 = DirectionRayCast(l__Torso__4.Position, (v77.Position - l__Torso__4.Position).unit, l__Value__13);
	if (v107 - l__Torso__4.Position).magnitude < (v77.CFrame.p - l__Torso__4.Position).magnitude then
		v77.CFrame = CFrame.new(v107);
	end;
end;
function enemyLost()
	if u12 <= 0 then

	else
		u12 = u12 - 1;
		return;
	end;
	u11 = "Pacing";
	u12 = 200;
	calculatePacing();
end;
l__Stats__5.EnemyFound.Changed:connect(function()
	if not l__Stats__5.EnemyFound.Value then
		u12 = 80;
		u11 = "Standing";
		u16 = nil;
		enemyLost();
	end;
end);
local u18 = nil;
local u19 = nil;
function checkDamage()
	local function v108(p24)
		local v109 = Instance.new("Explosion");
		v109.Position = p24.Main.Position;
		v109.BlastPressure = 0;
		v109.BlastRadius = 5;
		v109.Parent = l__CurrentCamera__1;
		l__Debris__2:AddItem(v109, 1);
		p24:BreakJoints();
		p24.Name = "Broken";
		local v110 = script.Parent:FindFirstChild("SoundScript");
		if v110 then
			v110 = Instance.new("StringValue");
			v110.Name = "Sound";
			v110.Value = "RoboticExplosion";
			local v111 = Instance.new("ObjectValue");
			v111.Name = "Location";
			v111.Value = l__Torso__4;
			v111.Parent = v110;
			v110.Parent = script.Parent.SoundScript.Effects;
		end;
		local function u20(p25)
			local v112 = p25:GetChildren();
			local v113 = #v112;
			local v114 = 1 - 1;
			while true do
				if v112[v114] then
					if v112[v114]:IsA("Part") then
						v112[v114].Velocity = Vector3.new(math.random(-20, 20), math.random(-20, 20), math.random(-20, 20));
					elseif v112[v114] then
						if v112[v114]:IsA("Model") then
							u20(v112[v114]);
						end;
					end;
				elseif v112[v114] then
					if v112[v114]:IsA("Model") then
						u20(v112[v114]);
					end;
				end;
				if 0 <= 1 then
					if v114 < v113 then

					else
						break;
					end;
				elseif v113 < v114 then

				else
					break;
				end;
				v114 = v114 + 1;			
			end;
		end;
		u20(p24);
		if l__CurrentCamera__1:findFirstChild("Level") then
			if l__CurrentCamera__1.Level:findFirstChild("Tool") then
				if p24:findFirstChild("Chaingun") then
					local u21 = p24:findFirstChild("Chaingun");
					coroutine.resume(coroutine.create(function()
						while true do
							task.wait(0.09);
							if not (u21.Velocity.magnitude < 0.1) then

							else
								break;
							end;						
						end;
						u21.Anchored = true;
					end));
					u21.Parent = l__CurrentCamera__1.Level.Tool;
				end;
			end;
		end;
	end;
	if l__Humanoid__3.MaxHealth / 4 <= l__Humanoid__3.Health then
		if l__Humanoid__3.Health < l__Humanoid__3.MaxHealth / 2 then
			if v14 then
				if l__Value__1:findFirstChild("RightArm") then
					v108(l__Value__1.RightArm);
				elseif not v14 then
					if l__Value__1:findFirstChild("LeftArm") then
						v108(l__Value__1.LeftArm);
					end;
				end;
			elseif not v14 then
				if l__Value__1:findFirstChild("LeftArm") then
					v108(l__Value__1.LeftArm);
				end;
			end;
			if not u18 then
				u18 = Instance.new("Smoke");
				u18.Color = Color3.new(0.3176470588235294, 0.3176470588235294, 0.3176470588235294);
				u18.Opacity = 0.2;
				u18.Size = 0.1;
				u18.Parent = l__Value__1.Main.Exhaust1;
				return;
			end;
		elseif l__Humanoid__3.Health < l__Humanoid__3.MaxHealth / 4 then
			if not v14 then
				if l__Value__1:findFirstChild("RightArm") then
					v108(l__Value__1.RightArm);
				elseif v14 then
					if l__Value__1:findFirstChild("LeftArm") then
						v108(l__Value__1.LeftArm);
					end;
				end;
			elseif v14 then
				if l__Value__1:findFirstChild("LeftArm") then
					v108(l__Value__1.LeftArm);
				end;
			end;
			if not u19 then
				u19 = Instance.new("Smoke");
				u19.Color = Color3.new(0.3176470588235294, 0.3176470588235294, 0.3176470588235294);
				u19.Opacity = 0.2;
				u19.Size = 0.1;
				u19.Parent = l__Value__1.Main.Exhaust2;
			end;
		end;
	elseif l__Humanoid__3.Health < l__Humanoid__3.MaxHealth / 4 then
		if not v14 then
			if l__Value__1:findFirstChild("RightArm") then
				v108(l__Value__1.RightArm);
			elseif v14 then
				if l__Value__1:findFirstChild("LeftArm") then
					v108(l__Value__1.LeftArm);
				end;
			end;
		elseif v14 then
			if l__Value__1:findFirstChild("LeftArm") then
				v108(l__Value__1.LeftArm);
			end;
		end;
		if not u19 then
			u19 = Instance.new("Smoke");
			u19.Color = Color3.new(0.3176470588235294, 0.3176470588235294, 0.3176470588235294);
			u19.Opacity = 0.2;
			u19.Size = 0.1;
			u19.Parent = l__Value__1.Main.Exhaust2;
		end;
	end;
end;
local u22 = l__Stats__5.OffsetMaxX.Value + l__Torso__4.Position.X;
local u23 = l__Stats__5.OffsetMaxZ.Value + l__Torso__4.Position.Z;
local u24 = l__Stats__5.OffsetMinX.Value + l__Torso__4.Position.X;
local u25 = l__Stats__5.OffsetMinZ.Value + l__Torso__4.Position.Z;
local u26 = 0;
local l__C1__27 = l__RightHip__7.C1;
local l__C1__28 = l__LeftHip__8.C1;
local l__C1__29 = l__Weld__9.C1;
local l__C1__30 = l__Weld__10.C1;
function move(p26)
	local v115, v116
	
	if u11 ~= "Standing" then
		if not u7 then
			v115 = 0.5;
			v116 = 4;
		else
			v115 = 0;
			v116 = 0;
		end;
	else
		v115 = 0;
		v116 = 0;
	end;
	local v117 = v115 * math.sin(p26 * v116);
	if 0.05 < math.abs(v117 - u26) then
		if u26 < v117 then
			v117 = u26 + 0.05;
		else
			v117 = u26 - 0.05;
		end;
	end;
	u26 = v117;
	l__RightHip__7.C1 = l__C1__27 * CFrame.Angles(-v117, 0, 0);
	l__LeftHip__8.C1 = l__C1__28 * CFrame.Angles(v117, 0, 0);
	l__Weld__9.C1 = l__C1__29 * CFrame.Angles(-v117 / 1.7 - 0.7, 0, 0);
	l__Weld__10.C1 = l__C1__30 * CFrame.Angles(v117 / 1.7 - 0.7, 0, 0);
end;
local u31 = 0;
local function u32()
	u11 = "Following";
	if u14 >= 0 then
		u16 = u13;
	end;
	if u17 > 3 and (u13.Position - l__Torso__4.Position).magnitude < u6 and l__Stats__5.Ammo.Value > 0 and checkSight(u13.Position) then
		if l__Value__1:findFirstChild("LeftArm") or l__Value__1:findFirstChild("RightArm") then
			if l__Value__1:findFirstChild("LeftArm") then
				onFireNormal(l__Value__1.LeftArm.Chaingun, u13);
			end;
			if l__Value__1:findFirstChild("RightArm") then
				onFireNormal(l__Value__1.RightArm.Chaingun, u13);
			end;
			l__Stats__5.Ammo.Value = l__Stats__5.Ammo.Value - 1;
		else
			onFireNormal(l__Head__5, u13);
		end;
		u17 = 0;
		return;
	end;
	if l__Value__13 < (u13.Position - l__Torso__4.Position).magnitude then
		u15();
	end;
end;
local function u33(p27)
	local v123
	
	if u22 < l__Torso__4.Position.X or u23 < l__Torso__4.Position.Z or l__Torso__4.Position.X < u24 or l__Torso__4.Position.Z < u25 then
		v77.CFrame = CFrame.new((u22 + u24) / 2, l__Torso__4.Position.Y, (u23 + u25) / 2);
		p27 = v77;
		u12 = 200;
		local v118, v119 = DirectionRayCast(l__Torso__4.Position, (v77.Position - l__Torso__4.Position).unit, l__Value__13);
		if v118 then
			task.wait(0.03);
			if math.random(1, 2) % 2 then
				local v120 = (u23 + u25) / 2;
				v77.CFrame = CFrame.new(l__Torso__4.Position.X, l__Torso__4.Position.Y, math.random(v120 - 4, v120 + 4));
				p27 = v77;
				local v121, v122 = DirectionRayCast(l__Torso__4.Position, (v77.Position - l__Torso__4.Position).unit, l__Value__13);
				v123 = v121;
			else
				local v124 = (u22 + u24) / 2;
				v77.CFrame = CFrame.new(math.random(v124 - 4, v124 + 4), l__Torso__4.Position.Y, l__Torso__4.Position.Z);
				p27 = v77;
				local v125, v126 = DirectionRayCast(l__Torso__4.Position, (v77.Position - l__Torso__4.Position).unit, l__Value__13);
				v123 = v125;
			end;
			if v123 then
				v77.CFrame = CFrame.new((u22 + u24) / 2, l__Torso__4.Position.Y, (u23 + u25) / 2);
				p27 = v77;
			end;
		end;
	end;
	l__Humanoid__3:MoveTo(p27.Position, p27);
end;
function runBot(p28)
	local v131 = 0
	
	move(p28);
	if 0 < l__Humanoid__3.Health then
		local v127 = nil;
		u31 = u31 + 1;
		if u31 == 10 then
			u31 = 0;
			findNearestTorso(l__Torso__4.Position);
		end;
		if u13 then
			l__Stats__5.State.Value = 2;
			l__Stats__5.EnemyFound.Value = true;
			u32();
		else
			l__Stats__5.State.Value = 1;
			if l__Stats__5.EnemyFound.Value then
				l__Stats__5.EnemyFound.Value = false;
			else
				enemyLost();
			end;
		end;
		if u16 then
			u33(u16);
			followEnemy(u16);
		else
			u33(l__Torso__4);
		end;
		checkDamage();
		local v128, v129, v130 = l__Torso__4.CFrame:toEulerAnglesXYZ();
		v127 = math.deg(v129 + math.pi / 2);
		if 0 < l__Torso__4.CFrame.lookVector.Z then
			v131 = v127 + 180;
		else
			v131 = 180 - v127;
		end;
		l__Stats__5.RadarRotation.Value = math.ceil(v131 + 180);
	else
		if u18 then
			u18:Destroy();
		end;
		if u19 then
			u19:Destroy();
		end;
		u11 = "Standing";
		u16 = nil;
	end;
	u17 = u17 + 1;
end;
checkAmmo();

task.wait(l__Stats__5.WaitTime.Value);

while l__Value__1 do
	local v132, v133 = wait();
	if script.Parent:findFirstChild("LocalScript") and script.Parent.LocalScript:findFirstChild("LocalPause") then
		if not script.Parent.LocalScript.LocalPause.Value then
			if l__Humanoid__3.WalkSpeed == 0 and l__Humanoid__3.Health > 0 and not u7 then
				l__Humanoid__3.WalkSpeed = l__Stats__5.Speed.Value;
			end;
			runBot(v133);
		elseif l__Humanoid__3.WalkSpeed ~= 0 then
			l__Humanoid__3.WalkSpeed = 0;
		end;
	else
		runBot(v133);
	end;
end;
